### ISSUE TITLE
Memory leak in SnapshotStateObserver?

### ISSUE THREAD

**Issue by bassstorm** [JetBrains/compose-jb#1969] opened 2022-03-20 17:04 UTC
Hi JB team,

I'm trying to get up with a desktop app which updates small part of UI quite frequently (e.g. a timer). As result of app's normal operation, memory consumption grows relatively quickly. Profiling points to `SnapshotStateObserver`, which seem doesn't release some state. However, I don't see a way how to control that or set a limit.

After just half an hour of work, memory trend is clear:
![image](https://user-images.githubusercontent.com/749825/159173373-2f9c4a64-a2e7-47eb-bc3e-6591cc31e553.png)

On below screenshot you may see Live Bytes and Objects, the max numbers there constantly grow:
![image](https://user-images.githubusercontent.com/749825/159173484-15341946-d511-4ba6-9f72-00e5599be14e.png)

Sample app source:
```
import androidx.compose.material.Text
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.ui.window.Window
import androidx.compose.ui.window.application
import kotlinx.datetime.Clock
import kotlin.concurrent.fixedRateTimer

fun main() = application {
    remember {
        fixedRateTimer(period = 50) { Holder.refreshClock() }
    }

    Window(onCloseRequest = ::exitApplication) {
        Text(Holder.clock.value)
    }
}

object Holder {
    val clock = mutableStateOf(Clock.System.now().toString())

    fun refreshClock() {
        clock.value = Clock.System.now().toString()
    }
}
```

OS: Manjaro Linux
Compose: 1.1.0
OpenJDK: 11.0.15

Looking forward hearing back from you. Thanks!

**Comment by bassstorm** [comment] 2022-03-24 19:45
A bit of extra details to add.

In `androidx.compose.runtime.snapshots.SnapshotStateObserver#observeReads`, `onValueChangedForScope` does seem always to be a new instance for my mutable state change event. So it leads to a situation when `applyMaps` list grows infinitely.

**Comment by XilinJia** [comment] 2022-03-29 21:36
This appears similar to a problem I have been investigating, though my problem occurs on Android with Jetpack Compose.  Some details [here](https://stackoverflow.com/questions/71600360/app-memory-leaks-likely-related-to-jetpack-compose-and-paging)

**Comment by mnonnenmacher** [comment] 2022-03-30 19:27
There is a related bug report for Jetpack Compose: https://issuetracker.google.com/issues/223222717

**Comment by bassstorm** [comment] 2022-03-30 19:44
@mnonnenmacher thanks for sharing, that's very good to know! Hopefully will be fixed soon in upstream.

**Comment by pema4** [comment] 2022-04-16 08:19
I believe the problem is in the [`UpdateEffect` composable](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:compose/ui/ui/src/desktopMain/kotlin/androidx/compose/ui/util/UpdateEffect.desktop.kt)

On every invocation of the [`performUpdate`](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:compose/ui/ui/src/desktopMain/kotlin/androidx/compose/ui/util/UpdateEffect.desktop.kt;l=53-60) `snapshotObserver` is subscribed with new lambda object:
```kotlin
fun performUpdate() {
    snapshotObserver.observeReads(
        Unit,
        onValueChangedForScope = { tasks.trySend(::performUpdate) }
    ) {
        currentUpdate()
    }
}
```

I replaced this declaration with the following and the memory leak disappeared:
```kotlin
lateinit var onValueChangedForScope: (Unit) -> Unit
fun performUpdate() {
    snapshotObserver.observeReads(
        Unit,
        onValueChangedForScope = onValueChangedForScope,
    ) {
        currentUpdate()
    }
}
onValueChangedForScope = { tasks.trySend(::performUpdate) }
```

**Comment by Thomas-Vos** [comment] 2022-04-22 12:33
I think I may be experiencing the same issue. My app slows down after time, so I started the Intellij debug view. After running the app for some time I paused it and took a look at the memory usage. I can see that there are lots of allocations of `androidx.compose.runtime.collection.IdentityArraySet`. See screenshot:
![Screenshot 2022-04-22 at 14 31 57](https://user-images.githubusercontent.com/11077217/164714777-5f39dcd5-fbcb-4b20-bfcd-448c70ebd841.png)

Is this expected? I am not sure. When looking at the stack trace of one of the objects I see the following:

![Screenshot 2022-04-22 at 14 32 39](https://user-images.githubusercontent.com/11077217/164714866-aeb07e5c-53f7-43f0-a6a4-6a8911821153.png)

**Comment by wznshuai** [comment] 2022-05-20 07:06
I ran into the same problem。
![image](https://user-images.githubusercontent.com/1897647/169472581-322df209-27c8-4608-ab5c-45fc9a7d8e2f.png)

**Comment by wangjunqiangongithub** [comment] 2022-06-29 10:17
![image](https://user-images.githubusercontent.com/45777969/176412848-f0bb188b-60d6-403a-b116-141a625c180f.png)

I have a similar problem, the snapshotmutablestateimpl has a memory leak problem, I'm a novice, and I don't know how to continue the analysis

**Comment by bassstorm** [comment] 2022-08-28 19:09
There's no real movement in related Google ticket: https://issuetracker.google.com/issues/223222717
Please vote or comment there if you can

**Comment by Ic-ks** [comment] 2022-10-14 17:46
I posted the following already at the google issue tracker:

The memory leak is still present in Compose 1.2.0 with Kotlin 1.7.20.
I profiled the code below (https://github.com/Ic-ks/compose-memory-leak) for 3 minutes with the Java Flight Recorder (the related .jfr file can be found here: https://issuetracker.google.com/action/issues/223222717/attachments/39334890?download=true). The overall allocated memory was more than 7GB. Heap usage steadily increased to 80 MB. It seems that `SnapshotStateObserver` does not clean its references properly.

```
val randomValueFlow = flow { while (true) emit(Math.random() * 100) }
    .onEach { delay(10) }
    .map { it.toInt() }
    .flowOn(Dispatchers.Default)

fun main() = application {
    Window(onCloseRequest = ::exitApplication) {
        val randomValue by randomValueFlow.collectAsState(0L)
        Text(text = randomValue.toString(), fontSize = 20.sp)
    }
}
```
![jfr](https://user-images.githubusercontent.com/29521057/195908628-e43a2505-cb66-4596-a8c8-6b9acfef9bcc.png)

PS: .jfr files can be viewed with JDK Mission Control (https://github.com/openjdk/jmc)

**Comment by yaroslavkulinich** [comment] 2022-11-04 20:46
I have the same issue. Constant high-frequency UI updates cause memory leak.
If the app is designed to be used for hours - there's no way to make it work without a restart.

**Comment by yaroslavkulinich** [comment] 2022-11-04 20:54
@pema4 Does your solution with gradle task patch works with Compose 1.2.0 version (maybe you already migrated)? 
Did you face any issues after patching UpdateEffect? 
I'm thinking to apply your approach, but it's nice to have some information about possible side-effects (if exist).
Thanks

**Comment by yaroslavkulinich** [comment] 2022-11-07 14:24
@igordmn please, take a closer look at this problem. 
The repository with the reproducer published here https://github.com/Ic-ks/compose-memory-leak shows the problem.
It would be perfect if the changes described by @pema4 were included directly in the jb-compose build. 
The problem for long-running high-frequency apps is HUGE.

**Comment by igordmn** [comment] 2022-11-07 14:29
Thanks for pointing to this issue, we'll take a look.

**Comment by igordmn** [comment] 2022-11-10 02:46
Thanks all for investigation of this issue! And especially @pema4 for the fix.

It is fixed, and the fix will be in 1.3.0 (or in 1.2.2, we will decide soon).

**Comment by bassstorm** [comment] 2022-11-10 19:00
Terrific! Can't wait for release!

**Closed** 2022-11-10 20:53 UTC
Labels: performance, p:critical

**Comment by okushnikov** [comment] 2024-08-26 15:51
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1969">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
