### ISSUE TITLE
How to remove a item in LazyColumn correctly?

### ISSUE THREAD

**Issue by sonder-joker** [JetBrains/compose-jb#338] opened 2021-01-31 13:13 UTC
I try to write some test code to check if i can delete a item in a column
```kotlin
fun main() {
    val list = mutableStateListOf("a", "b", "c")
    Window {
        LazyColumn {
            itemsIndexed(list) { index, item ->
                Button({
                    list.removeAt(index)
                }) {
                    Text(item)
                }
            }
        }
    }
}
```
but i got 
```
Java HotSpot(TM) 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
Exception in thread "AWT-EventQueue-0" java.lang.IndexOutOfBoundsException: index: 2, size: 2
	at kotlinx.collections.immutable.internal.ListImplementation.checkElementIndex$kotlinx_collections_immutable(ListImplementation.kt:15)
	at kotlinx.collections.immutable.implementations.immutableList.SmallPersistentVector.get(SmallPersistentVector.kt:146)
	at androidx.compose.runtime.snapshots.SnapshotStateList.get(SnapshotStateList.kt:71)
	at com.youngerhousea.miraidesktop.TestKt$main$1$1$1$invoke$$inlined$itemsIndexed$1.invoke(LazyDsl.kt:81)
	at com.youngerhousea.miraidesktop.TestKt$main$1$1$1$invoke$$inlined$itemsIndexed$1.invoke(LazyDsl.kt)
	at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt:174)
	at androidx.compose.runtime.internal.ComposableLambda$invoke$2.invoke(ComposableLambda.kt:180)
	at androidx.compose.runtime.internal.ComposableLambda$invoke$2.invoke(ComposableLambda.kt)
	at androidx.compose.runtime.RecomposeScopeImpl.compose(RecomposeScopeImpl.kt:104)
	at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(Composer.kt:2306)
	at androidx.compose.runtime.ComposerImpl.skipCurrentGroup(Composer.kt:2553)
	at androidx.compose.runtime.ComposerImpl.recompose$runtime(Composer.kt:2679)
	at androidx.compose.runtime.CompositionImpl.recompose(Composition.kt:306)
	at androidx.compose.runtime.Recomposer.performRecompose(Recomposer.kt:480)
	at androidx.compose.runtime.Recomposer.access$performRecompose(Recomposer.kt)
	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$4.invoke(Recomposer.kt:393)
	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$4.invoke(Recomposer.kt)
	at androidx.compose.runtime.BroadcastFrameClock$FrameAwaiter.resume(BroadcastFrameClock.kt:41)
	at androidx.compose.runtime.BroadcastFrameClock.sendFrame(BroadcastFrameClock.kt:65)
	at androidx.compose.ui.platform.DesktopOwners.onFrame(DesktopOwners.kt:112)
	at androidx.compose.desktop.ComposeLayer$1.onRender(ComposeLayer.kt:123)
	at org.jetbrains.skiko.SkiaLayer.update$skiko$suspendImpl(SkiaLayer.kt:103)
	at org.jetbrains.skiko.SkiaLayer.update$skiko(SkiaLayer.kt)
	at org.jetbrains.skiko.redrawer.WindowsRedrawer$update$2.invokeSuspend(WindowsRedrawer.kt:44)
	at org.jetbrains.skiko.redrawer.WindowsRedrawer$update$2.invoke(WindowsRedrawer.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:161)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at org.jetbrains.skiko.redrawer.WindowsRedrawer.update(WindowsRedrawer.kt:43)
	at org.jetbrains.skiko.redrawer.WindowsRedrawer$Companion$frameDispatcher$1.invokeSuspend(WindowsRedrawer.kt:69)
	at org.jetbrains.skiko.redrawer.WindowsRedrawer$Companion$frameDispatcher$1.invoke(WindowsRedrawer.kt)
	at org.jetbrains.skiko.FrameDispatcher$job$1.invokeSuspend(FrameDispatcher.kt:22)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at java.desktop/java.awt.event.InvocationEvent.dispatch$$$capture(InvocationEvent.java:316)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```
What's wrong with my code or it's a bug?

**Comment by jimgoog** [comment] 2021-01-31 17:19
cc @ chuckjaz

**Comment by jimgoog** [comment] 2021-01-31 17:20
cc @chuckjaz

**Comment by olonho** [comment] 2021-02-01 08:54
Indeed looks like a problem.

**Comment by andkulikov** [comment] 2021-02-01 15:23
It is not desktop specific and tracked here: https://issuetracker.google.com/issues/163069767

**Comment by andkulikov** [comment] 2021-02-01 15:23
Replacing mutableStateListOf with a mutableStateOf(listOf<TodoItem>()) is a workaround to avoid this crash for now

**Comment by akurasov** [comment] 2021-07-16 09:54
Fix in Jetpack. To check in CMP.

**Comment by akurasov** [comment] 2021-07-23 14:02
Works fine in build262. Closing.

**Closed by akurasov** 2021-07-23 14:02 UTC
Labels: bug, discussion, google

**Comment by Exidel** [comment] 2021-07-23 16:16
@akurasov Actually if selected last element of the mutableStateListOf() when you delete this element it throw the exception `IndexOutOfBoundsException`

**Comment by akurasov** [comment] 2021-07-26 08:55
I used mutableStateListOf and there is no IOBException whatever item I remove. Could you share your code?

**Comment by Exidel** [comment] 2021-07-26 10:24
Can't reproduce it in test. Look like i'm screwed up somewhere in my own code. Sorry.

**Comment by akurasov** [comment] 2021-07-26 10:42
NP :). Keep it closed then.

**Comment by Exidel** [comment] 2021-07-27 07:51
I reproduced the issue and found reason why it happening.


https://user-images.githubusercontent.com/80458677/127114730-0eb3bec2-951e-49a2-847c-3c73108d0d61.mp4

<details>
<summary>Code</summary>

```
import androidx.compose.foundation.*
import androidx.compose.foundation.layout.*
import androidx.compose.material.ContextMenu
import androidx.compose.material.Text
import androidx.compose.runtime.*
import androidx.compose.runtime.snapshots.SnapshotStateList
import androidx.compose.ui.Alignment
import androidx.compose.ui.ExperimentalComposeUiApi
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.dp
import androidx.compose.ui.window.*

data class Content(val content: String)

@OptIn(ExperimentalFoundationApi::class)
@ExperimentalComposeUiApi
fun main() = application {


    var index by remember { mutableStateOf(0) }
    val composeList = mutableStateListOf<Content>(
                                                    Content("content1"),
                                                    Content("content2"),
                                                    Content("content3")
                                                )

    val mainWin = rememberWindowState( size = WindowSize(300.dp, 200.dp), position = WindowPosition(Alignment.Center) )

    Window( onCloseRequest = { exitApplication() }, state = mainWin, title = "TEST" ) {

        LeftSide( composeList, index, { index = it } )
        RightSide( composeList, index )

    }

}


@OptIn(ExperimentalFoundationApi::class)
@Composable
fun LeftSide(composeList: SnapshotStateList<Content>, index: Int, indexLamb: (Int) -> Unit) {

    var open by remember { mutableStateOf(false) }
    var del by remember { mutableStateOf(false) }

    Column(Modifier.size(100.dp, 150.dp).border(4.dp, Color.Blue)) {
        for (i in 0..composeList.lastIndex) {
            Text("item$i", textAlign = TextAlign.Center, modifier = Modifier
                .padding(top = 20.dp)
                .fillMaxWidth()
                .combinedClickable(
                    onClick = { indexLamb(i) },
                    onLongClick = { indexLamb(i); open = true }
                )
            )
        }
    }

    if (open) {
        EditMenu(open, {open=it}, {del=it})
    }

    if (del) {
        composeList.removeAt(index)
        indexLamb(index-1)
        del = false
    }

}


@Composable
fun RightSide(composeList: SnapshotStateList<Content>, index: Int) {

    Box(Modifier.padding(start = 150.dp).size(150.dp, 150.dp).border(4.dp, Color.Red)) {
        Column(Modifier.align(Alignment.Center)) {
            if (composeList.size > 0) {
                Text(text = composeList[index].content)
            } else {
                Text(text = "list is empty")
            }
        }
    }

}


@Composable
fun EditMenu(open: Boolean, openLamb: (Boolean) -> Unit, delLamb: (Boolean) -> Unit) {

    ContextMenu(
        expanded = open,
        onDismissRequest = { openLamb(false) }
    ) {

        Text("Delete", Modifier.clickable {
            delLamb(true)
            openLamb(false)
        } )

    }

}
```

</details>

The reason is using Boolean variable to trigger list.removeAt(index) function or just if() function (not sure). If I use list.removeAt(index) currently inside ContextMenu all work fine.

```
@Composable
fun EditMenu(open: Boolean, openLamb: (Boolean) -> Unit, delLamb: (Boolean) -> Unit, index: Int, indexLamb: (Int) -> Unit, composeList: SnapshotStateList<Content>) {

    ContextMenu(
        expanded = open,
        onDismissRequest = { openLamb(false) }
    ) {

        Text("Delete", Modifier.clickable {
//            delLamb(true)
            composeList.removeAt(index)
            indexLamb(index-1)
            openLamb(false)
        } )

    }

}
```

But if I remember right documentation recommend move out all logic from composable functions.

**Comment by akurasov** [comment] 2021-07-27 08:15
@Exidel the issue is that you modify the list during Composition. 
The exception is from from RightSide:Text(text = composeList[index].content)

The RightSide is called with certain index, but when it is being executed there is no composeList[index] anymore. It is not a Compose issue :)

**Comment by Exidel** [comment] 2021-07-27 09:05
> The RightSide is called with certain index, but when it is being executed there is no composeList[index] anymore. It is not a Compose issue :)

Don't understand clearly why same code inside ContextMenu doesn't provoke IOBException then and how to replace this code from ContextMenu to make it reusable?

**Comment by akurasov** [comment] 2021-07-27 09:13
Where in ContextMenu do you use composeList[index]? I can't see it...

**Comment by Exidel** [comment] 2021-07-27 09:21
I mean which diffirence in deleting element inside LeftSide() or ContextMenu() functions both does the same. But only LeftSide() trigger that exception.

**Comment by akurasov** [comment] 2021-07-27 09:24
I'm not sure I understand your question. What is for sure - it is very bad idea to modify data inside LeftSide(). All data modification should be done inside callbacks.

**Comment by Exidel** [comment] 2021-07-27 09:31
> All data modification should be done inside callbacks.

I got it. Thank you.

**Comment by himanshurv18** [comment] 2024-02-03 13:15
package com.example.wishlistapp

import android.annotation.SuppressLint
import android.util.Log
import android.widget.Toast
import androidx.compose.animation.animateColorAsState
import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material.Card
import androidx.compose.material.DismissDirection
import androidx.compose.material.DismissValue
import androidx.compose.material.ExperimentalMaterialApi
import androidx.compose.material.FloatingActionButton
import androidx.compose.material.Icon
import androidx.compose.material.Scaffold
import androidx.compose.material.SwipeToDismiss
import androidx.compose.material.Text
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.Add
import androidx.compose.material.icons.filled.Delete
import androidx.compose.material.rememberDismissState
import androidx.compose.runtime.Composable
import androidx.compose.runtime.collectAsState
import androidx.compose.runtime.getValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.material.*
import androidx.compose.material.DismissValue.DismissedToEnd
import androidx.compose.runtime.DisposableEffect
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.derivedStateOf
import androidx.compose.runtime.mutableStateListOf
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.rememberUpdatedState
import androidx.compose.runtime.setValue
import androidx.navigation.NavController
import com.example.wishlistapp.Data.Wish



@SuppressLint("UnrememberedMutableState", "RememberReturnType")
@OptIn(ExperimentalMaterialApi::class)
@Composable
fun HomeView(
    navController: NavController,
    viewModel: WishViewModel
){

    val context = LocalContext.current
    val scaffoldState = rememberScaffoldState()
    Scaffold(
        scaffoldState = scaffoldState,
        topBar = { AppBarView(title = "WishList") },
        floatingActionButton = {
            FloatingActionButton(
                modifier = Modifier.padding(all = 20.dp),
                contentColor = Color.White,
                backgroundColor = Color.Black,
                onClick = {
                    Toast.makeText(context, "FAButton Clicked", Toast.LENGTH_LONG).show()
                    navController.navigate(Screen.AddScreen.route + "/0L")

                }) {
                Icon(imageVector = Icons.Default.Add, contentDescription = null)
            }
        }

    ) {

        val wishlist =  viewModel.getAllWishes.collectAsState(initial = listOf())



        Log.e("HomeScreen", "Outside items: ${wishlist.value}")

        LazyColumn(modifier = Modifier
            .fillMaxSize()
            .padding(it)){
            items(wishlist.value, key={wish-> wish.id} ){
                    wish ->
                Log.e("HomeScreen", "Inside items: ${wishlist.value}")
                val dismissState = rememberDismissState(
                    confirmStateChange = {
                        if(it == DismissValue.DismissedToEnd || it== DismissValue.DismissedToStart){
                            viewModel.deleteWish(wish)
                        }
                        true
                    }
                )

                SwipeToDismiss(
                    state = dismissState,
                    background = {
                        val color by animateColorAsState(
                            if(dismissState.dismissDirection
                                == DismissDirection.EndToStart) Color.Red else Color.Transparent
                            ,label = ""
                        )
                        val alignment = Alignment.CenterEnd
                        Box(
                            Modifier.fillMaxSize().background(color).padding(horizontal = 20.dp),
                            contentAlignment = alignment
                        ){
                            Icon(Icons.Default.Delete,
                                contentDescription = "Delete Icon",
                                tint = Color.White)
                        }

                    },
                    directions = setOf(DismissDirection.EndToStart),
                    dismissThresholds = {FractionalThreshold(1f)},
                    dismissContent = {
                        WishItem(wish = wish) {
                            val id = wish.id
                            navController.navigate(Screen.AddScreen.route + "/$id")
                        }
                    }
                )
            }
        }


    }
}



@Composable
fun WishItem(wish: Wish, onClick: () -> Unit){
    Card(modifier = Modifier
        .fillMaxWidth()
        .padding(top = 8.dp, start = 8.dp, end = 8.dp)
        .clickable {
            onClick()
        },
        elevation = 10.dp,
        backgroundColor = Color.White
    ) {
        Column(modifier = Modifier.padding(16.dp)){
            Text(text = wish.title, fontWeight = FontWeight.ExtraBold)
            Text(text = wish.description)
        }
    }
}



i also get   java.lang.IndexOutOfBoundsException error when i delete a item from the screen.



can anyone help me?
