### ISSUE TITLE
View events are triggered on non-main thread?

### ISSUE THREAD

**Issue by arkivanov** [JetBrains/compose-jb#348] opened 2021-02-04 00:57 UTC
Hello! I'm observing an interesting behaviour. The following code:

```kotlin
println(Thread.currentThread().toString())

    Window("Title") {
        Surface(modifier = Modifier.fillMaxSize()) {
            MaterialTheme {
                DesktopTheme {
                    Button(onClick = { println(Thread.currentThread().toString()) }) {
                        Text("Button")
                    }
                }
            }
        }
    }
```

prints:

```
Thread[main,5,main]
Thread[AWT-EventQueue-0 @coroutine#1,6,main]
```

Is it expected? My concern is that some libraries have requirements that they are accessed from the same thread as they were initialised. From my point of view, the event queue should be looped from the original main thread.

**Comment by kirill-grouchnikov** [comment] 2021-02-04 01:05
All UI events should be dispatched on the AWT thread, so the second one is correct. And probably the `Window` element and all its view creation happens deferred on the AWT thread as well. So your first logging statement doesn't capture the right thread.

**Comment by arkivanov** [comment] 2021-02-04 01:09
Right. How can we initialize on the AWT thread?

**Comment by kirill-grouchnikov** [comment] 2021-02-04 01:34
That's already being done for you - https://github.com/androidx/androidx/blob/androidx-main/compose/ui/ui/src/desktopMain/kotlin/androidx/compose/desktop/AppWindow.kt#L72

**Comment by kirill-grouchnikov** [comment] 2021-02-04 01:35
If you want to run some library code on the same thread, that would be either `SwingUtilities.invokeLater` or a `GlobalScope.launch(Dispatchers.Swing)` block

**Comment by arkivanov** [comment] 2021-02-04 01:39
Thanks! Given the original example, how I should change it so it would always print the AWT thread?

**Comment by kirill-grouchnikov** [comment] 2021-02-04 02:12
Depends on what you want to do and when you want it to be done. There's `WindowEvents` that you can pass to the `Window` composable, and it has `onOpen` callback among others.

**Comment by jimgoog** [comment] 2021-02-04 03:03
Let me jump in real quick to clarify what is guaranteed and what is explicitly NOT guaranteed.

What is guaranteed:

-  UI Events, including button clicks, will fire on the AWT thread.
-  When using the new [SwingPanel API](https://android-review.googlesource.com/c/platform/frameworks/support/+/1559240), the initialization lambda and update lambdas will be invoked on the AWT thread.
-  Visual updates will be applied on the AWT thread.

As Kirill mentioned, you can jump on the AWT thread using various functions provided by `SwingUtilities`

Virtually nothing else about threading is guaranteed.  In fact, Composition is explicitly NOT guaranteed to occur on any particular thread.  There isn't even a guarantee that a child widget will be composed on the same thread that a parent is being composed on.  You should NOT be making any assumptions that depend upon the thread that your composable functions are running in.

I'm going to close this issue because this is working as intended (thus not actionable).  Feel free to continue the discussion in this thread.

**Closed by jimgoog** 2021-02-04 03:03 UTC

**Comment by kirill-grouchnikov** [comment] 2021-02-04 03:41
Arkadii - I think that it would be helpful to be a little bit more specific about the scenarios that you have in mind. Maybe it's for Compose in general, maybe it's for Compose for Desktop in particular, maybe it's about how the existing window callbacks are not addressing the specific requirements that you have in mind

**Comment by arkivanov** [comment] 2021-02-04 10:28
@jimgoog thanks for clarifying. My concern was about the `main` function. It is **not** Composable, and so I expected it to be called on the main thread, the same thread that will be used later for Compose callbacks etc.

The issue here is that I need to initialise some dependencies before the composition will begin, and pass them later to Composable functions (directly or via ambients, whatever). I need to initialise dependencies on the same thread as they will be called later from callbacks.

**Comment by jimgoog** [comment] 2021-02-04 11:32
> My concern was about the main function. It is not Composable, and so I expected it to be called on the main thread, the same thread that will be used later for Compose callbacks etc.
 
Yeah, Compose is not doing anything special here.  The main thread is used as an entry point for a Java application, and the AWT thread is used for graphics/UI operations.  This is done largely because you don't want the main thread to cause the UI to become unresponsive, and you don't want apps which don't have/need a UI to inherit the complexity of an imposed event queue.  We're just doing conforming to the de facto standard here.

> The issue here is that I need to initialise some dependencies before the composition will begin, and pass them later to Composable functions (directly or via ambients, whatever). I need to initialise dependencies on the same thread as they will be called later from callbacks.

Without knowing what those dependencies are, let me say that this makes me a tiny bit nervous.  You don't want to be doing any meaningful amount of work on the AWT thread, as you will block UI responsiveness.  You may want to consider dispatching the UI event from the AWT thread to a data thread that you own.  But I say this without knowing anything about your dependencies, so maybe it's fine.

Also, ambients are a major foot gun, please avoid using them to the extent possible, just like you avoid globals or ThreadLocals.

**Comment by arkivanov** [comment] 2021-02-04 12:04
@jimgoog A common scenario of app startup is:

```kotlin
fun main() {
    val myViewModel = MyViewModel() // Initialise the ViewModel, I want this to run on AWT/Event thread, from which it will be accessed later

    Window("Title") {
        Surface(modifier = Modifier.fillMaxSize()) {
            MaterialTheme {
                DesktopTheme {
                    Button(onClick = { 
                        viewModel.onButtonClick() // Runs on AWT/Event thread, fine
                    }) {
                        Text("Button")
                    }
                }
            }
        }
    }
}
```

In my particular case I want the ViewModel to be instantiated on the same thread, from which it will be accessed later. From my little experience with native desktop apps, the event looper runs on the same thread as the `main` function. So this was never a problem for me.

E.g. in native GTK apps we have something like this:

```kotlin
fun main() {
    val app: CPointer<GtkApplication> = gtk_application_new(...).requireNotNull()
    // Initialise other things here, this is the main thread

    g_application_run(app.reinterpret(), 0, null) // <-- This function loops on the exact same main thread
    
    // Cleanups
}
```

**Comment by arkivanov** [comment] 2021-02-04 12:06
I can make `lateinit val myViewModel` initialise it from something like `DisposableEffect`. This should work, but looks fragile.

**Comment by jimgoog** [comment] 2021-02-04 12:08
I suppose my question was more "what are you doing in ViewModel that forces it to be on the same thread?"

**Comment by arkivanov** [comment] 2021-02-04 12:16
@jimgoog I am using an SDK that does this verification. Fortunately, I can lift this restriction in my particular case, but this still might be a use case in general. Like "I want this class to be instantiated on the AWT/Event thread". E.g. it my trigger some side effects, which are out of control of the developer.

**Comment by jimgoog** [comment] 2021-02-04 12:19
Yeah, if you really need to run on AWT, using DisposableEffect doesn't really sound like the right thing, I'd do something like:

```
    val viewModel = run {
        var viewModel: MyViewModel? = null
        SwingUtilities.invokeAndWait { viewModel = MyViewModel() }
        viewModel!!
    }
```

**Comment by arkivanov** [comment] 2021-02-04 12:22
@jimgoog Thanks! This is what I was looking for! I will try.

**Comment by okushnikov** [comment] 2024-08-26 17:43
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6478">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
