### ISSUE TITLE
IntelliJ IDEA fails to suggest imports for `remember` delegate

### ISSUE THREAD

**Issue by SebastianAigner** [JetBrains/compose-jb#849] opened 2021-07-04 14:13 UTC
![image](https://user-images.githubusercontent.com/2178959/124388259-78108400-dce2-11eb-94a9-0f7c3de6f56c.png)

None of the suggestions provided allow us to import the following imports automatically, which are required for the snippet in the screenshot to work. Only the following error message is present:

```
Type 'TypeVariable(T)' has no method 'getValue(Nothing?, KProperty<*>)' and thus it cannot serve as a delegate
```

![image](https://user-images.githubusercontent.com/2178959/124388340-c9207800-dce2-11eb-920b-2ed2c729399e.png)

```
import androidx.compose.runtime.getValue
import androidx.compose.runtime.setValue
```

(As seen in the CFW template example)

**Comment by igordmn** [comment] 2021-07-06 11:05
[The issue in Kotlin tracker](https://youtrack.jetbrains.com/issue/KTIJ-16966).

Probably it is fixed in the latest Kotlin plugin (but there is no public release yet for stable IDEA 2021.1.3).

**Comment by akurasov** [comment] 2021-08-17 11:56
This is a duplicate of https://github.com/JetBrains/compose-jb/issues/142

**Closed by akurasov** 2021-08-17 11:56 UTC
Labels: bug, ide

**Comment by okushnikov** [comment] 2024-07-14 17:37
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5371">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
