### ISSUE TITLE
Composable function passed to Window is called two times at the application startup

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-jb#87] opened 2020-11-11 13:54 UTC
```
import androidx.compose.desktop.Window

fun main() = Window {
    println("Window")
}
```

On the version "0.1.0-build113" there is two messages in the console.
On the version "0.1.0-m1-build62" - only one message.

See also https://github.com/JetBrains/compose-jb/issues/86 ("Navigation now does not work")

**Comment by olonho** [comment] 2020-11-11 16:46
First call:
``
invoke:35, MainKt$main$2 (example.todo.desktop)
invoke:-1, MainKt$main$2 (example.todo.desktop)
invoke:146, ComposableLambda (androidx.compose.runtime.internal)
invoke:-1, ComposableLambda (androidx.compose.runtime.internal)
invoke:64, AppWindowKt$Window$1$1 (androidx.compose.desktop)
invoke:-1, AppWindowKt$Window$1$1 (androidx.compose.desktop)
invoke:146, ComposableLambda (androidx.compose.runtime.internal)
invoke:-1, ComposableLambda (androidx.compose.runtime.internal)
invoke:255, AppWindow$show$1 (androidx.compose.desktop)
invoke:-1, AppWindow$show$1 (androidx.compose.desktop)
invoke:146, ComposableLambda (androidx.compose.runtime.internal)
invoke:-1, ComposableLambda (androidx.compose.runtime.internal)
Providers:187, AmbientKt (androidx.compose.runtime)
invoke:239, AppWindow$onCreate$1 (androidx.compose.desktop)
invoke:-1, AppWindow$onCreate$1 (androidx.compose.desktop)
invoke:146, ComposableLambda (androidx.compose.runtime.internal)
invoke:-1, ComposableLambda (androidx.compose.runtime.internal)
invoke:123, DesktopSelectionKt$DesktopSelectionContainer$4$1 (androidx.compose.ui.platform)
invoke:-1, DesktopSelectionKt$DesktopSelectionContainer$4$1 (androidx.compose.ui.platform)
invoke:146, ComposableLambda (androidx.compose.runtime.internal)
invoke:-1, ComposableLambda (androidx.compose.runtime.internal)
Layout:114, LayoutKt (androidx.compose.ui.layout)
Wrap:38, DesktopSelectionKt (androidx.compose.ui.platform)
access$Wrap:-1, DesktopSelectionKt (androidx.compose.ui.platform)
invoke:122, DesktopSelectionKt$DesktopSelectionContainer$4 (androidx.compose.ui.platform)
invoke:-1, DesktopSelectionKt$DesktopSelectionContainer$4 (androidx.compose.ui.platform)
invoke:146, ComposableLambda (androidx.compose.runtime.internal)
invoke:-1, ComposableLambda (androidx.compose.runtime.internal)
Providers:187, AmbientKt (androidx.compose.runtime)
DesktopSelectionContainer:121, DesktopSelectionKt (androidx.compose.ui.platform)
DesktopSelectionContainer:62, DesktopSelectionKt (androidx.compose.ui.platform)
invoke:36, WrapperKt$setContent$1$1 (androidx.compose.ui.platform)
invoke:-1, WrapperKt$setContent$1$1 (androidx.compose.ui.platform)
invoke:146, ComposableLambda (androidx.compose.runtime.internal)
invoke:-1, ComposableLambda (androidx.compose.runtime.internal)
Providers:187, AmbientKt (androidx.compose.runtime)
ProvideCommonAmbients:118, AmbientsKt (androidx.compose.ui.platform)
invoke:58, WrapperKt$ProvideDesktopAmbients$1 (androidx.compose.ui.platform)
invoke:-1, WrapperKt$ProvideDesktopAmbients$1 (androidx.compose.ui.platform)
invoke:146, ComposableLambda (androidx.compose.runtime.internal)
invoke:-1, ComposableLambda (androidx.compose.runtime.internal)
Providers:187, AmbientKt (androidx.compose.runtime)
ProvideDesktopAmbients:54, WrapperKt (androidx.compose.ui.platform)
access$ProvideDesktopAmbients:-1, WrapperKt (androidx.compose.ui.platform)
invoke:35, WrapperKt$setContent$1 (androidx.compose.ui.platform)
invoke:-1, WrapperKt$setContent$1 (androidx.compose.ui.platform)
invoke:146, ComposableLambda (androidx.compose.runtime.internal)
invoke:-1, ComposableLambda (androidx.compose.runtime.internal)
invokeComposable:2887, ComposerKt (androidx.compose.runtime)
composeInitial:2057, Composer (androidx.compose.runtime)
composeInitial$runtime:337, Recomposer (androidx.compose.runtime)
setContent:110, CompositionImpl (androidx.compose.runtime)
setContent:34, WrapperKt (androidx.compose.ui.platform)
setContent:31, WrapperKt (androidx.compose.desktop)
onCreate:238, AppWindow (androidx.compose.desktop)
show:253, AppWindow (androidx.compose.desktop)
run:63, AppWindowKt$Window$1 (androidx.compose.desktop)
dispatch:313, InvocationEvent (java.awt.event)
dispatchEventImpl:770, EventQueue (java.awt)
run:721, EventQueue$4 (java.awt)
run:715, EventQueue$4 (java.awt)
executePrivileged:751, AccessController (java.security)
doPrivileged:389, AccessController (java.security)
doIntersectionPrivilege:85, ProtectionDomain$JavaSecurityAccessImpl (java.security)
dispatchEvent:740, EventQueue (java.awt)
pumpOneEventForFilters:203, EventDispatchThread (java.awt)
pumpEventsForFilter:124, EventDispatchThread (java.awt)
pumpEventsForHierarchy:113, EventDispatchThread (java.awt)
pumpEvents:109, EventDispatchThread (java.awt)
pumpEvents:101, EventDispatchThread (java.awt)
run:90, EventDispatchThread (java.awt)
``

second call

``
invoke:35, MainKt$main$2 (example.todo.desktop)
invoke:-1, MainKt$main$2 (example.todo.desktop)
invoke:146, ComposableLambda (androidx.compose.runtime.internal)
invoke:-1, ComposableLambda (androidx.compose.runtime.internal)
invoke:64, AppWindowKt$Window$1$1 (androidx.compose.desktop)
invoke:-1, AppWindowKt$Window$1$1 (androidx.compose.desktop)
invoke:146, ComposableLambda (androidx.compose.runtime.internal)
invoke:-1, ComposableLambda (androidx.compose.runtime.internal)
invoke:255, AppWindow$show$1 (androidx.compose.desktop)
invoke:-1, AppWindow$show$1 (androidx.compose.desktop)
invoke:146, ComposableLambda (androidx.compose.runtime.internal)
invoke:-1, ComposableLambda (androidx.compose.runtime.internal)
Providers:187, AmbientKt (androidx.compose.runtime)
invoke:239, AppWindow$onCreate$1 (androidx.compose.desktop)
invoke:-1, AppWindow$onCreate$1 (androidx.compose.desktop)
invoke:146, ComposableLambda (androidx.compose.runtime.internal)
invoke:-1, ComposableLambda (androidx.compose.runtime.internal)
invoke:123, DesktopSelectionKt$DesktopSelectionContainer$4$1 (androidx.compose.ui.platform)
invoke:-1, DesktopSelectionKt$DesktopSelectionContainer$4$1 (androidx.compose.ui.platform)
invoke:146, ComposableLambda (androidx.compose.runtime.internal)
invoke:-1, ComposableLambda (androidx.compose.runtime.internal)
Layout:114, LayoutKt (androidx.compose.ui.layout)
Wrap:38, DesktopSelectionKt (androidx.compose.ui.platform)
access$Wrap:-1, DesktopSelectionKt (androidx.compose.ui.platform)
invoke:122, DesktopSelectionKt$DesktopSelectionContainer$4 (androidx.compose.ui.platform)
invoke:-1, DesktopSelectionKt$DesktopSelectionContainer$4 (androidx.compose.ui.platform)
invoke:146, ComposableLambda (androidx.compose.runtime.internal)
invoke:-1, ComposableLambda (androidx.compose.runtime.internal)
Providers:187, AmbientKt (androidx.compose.runtime)
DesktopSelectionContainer:121, DesktopSelectionKt (androidx.compose.ui.platform)
DesktopSelectionContainer:62, DesktopSelectionKt (androidx.compose.ui.platform)
invoke:36, WrapperKt$setContent$1$1 (androidx.compose.ui.platform)
invoke:-1, WrapperKt$setContent$1$1 (androidx.compose.ui.platform)
invoke:146, ComposableLambda (androidx.compose.runtime.internal)
invoke:-1, ComposableLambda (androidx.compose.runtime.internal)
Providers:187, AmbientKt (androidx.compose.runtime)
ProvideCommonAmbients:118, AmbientsKt (androidx.compose.ui.platform)
invoke:58, WrapperKt$ProvideDesktopAmbients$1 (androidx.compose.ui.platform)
invoke:-1, WrapperKt$ProvideDesktopAmbients$1 (androidx.compose.ui.platform)
invoke:146, ComposableLambda (androidx.compose.runtime.internal)
invoke:-1, ComposableLambda (androidx.compose.runtime.internal)
Providers:187, AmbientKt (androidx.compose.runtime)
ProvideDesktopAmbients:54, WrapperKt (androidx.compose.ui.platform)
access$ProvideDesktopAmbients:-1, WrapperKt (androidx.compose.ui.platform)
invoke:35, WrapperKt$setContent$1 (androidx.compose.ui.platform)
invoke:-1, WrapperKt$setContent$1 (androidx.compose.ui.platform)
invoke:146, ComposableLambda (androidx.compose.runtime.internal)
invoke:-1, ComposableLambda (androidx.compose.runtime.internal)
compose:286, RecomposeScope (androidx.compose.runtime)
recomposeToGroupEnd:1696, Composer (androidx.compose.runtime)
skipCurrentGroup:1953, Composer (androidx.compose.runtime)
recompose:2083, Composer (androidx.compose.runtime)
performRecompose:359, Recomposer (androidx.compose.runtime)
access$performRecompose:-1, Recomposer (androidx.compose.runtime)
invoke:294, Recomposer$recomposeAndApplyChanges$2$3 (androidx.compose.runtime)
invoke:-1, Recomposer$recomposeAndApplyChanges$2$3 (androidx.compose.runtime)
withFrameNanos:30, ActualDesktopKt$DefaultMonotonicFrameClock$2$1 (androidx.compose.runtime.dispatch)
resumeWith:33, BaseContinuationImpl (kotlin.coroutines.jvm.internal)
run:56, DispatchedTask (kotlinx.coroutines)
dispatch:313, InvocationEvent (java.awt.event)
dispatchEventImpl:770, EventQueue (java.awt)
run:721, EventQueue$4 (java.awt)
run:715, EventQueue$4 (java.awt)
executePrivileged:751, AccessController (java.security)
doPrivileged:389, AccessController (java.security)
doIntersectionPrivilege:85, ProtectionDomain$JavaSecurityAccessImpl (java.security)
dispatchEvent:740, EventQueue (java.awt)
pumpOneEventForFilters:203, EventDispatchThread (java.awt)
pumpEventsForFilter:124, EventDispatchThread (java.awt)
pumpEventsForHierarchy:113, EventDispatchThread (java.awt)
pumpEvents:109, EventDispatchThread (java.awt)
pumpEvents:101, EventDispatchThread (java.awt)
run:90, EventDispatchThread (java.awt)
``

**Comment by olonho** [comment] 2020-11-12 09:43
Fixed in `0.1.0-build119`.

**Closed by olonho** 2020-11-12 09:43 UTC

**Comment by ScottPierce** [comment] 2020-11-13 21:44
@olonho How did you get that call trace in the log for each of the calls?

**Comment by Omnieboer** [comment] 2021-02-26 14:59
This is happening for me again in 
```kts
plugins {
    kotlin("jvm") version "1.4.30"
    id("org.jetbrains.compose") version "0.3.0"
}
```

**Comment by igordmn** [comment] 2021-02-26 15:07
> This is happening for me again in

Can you tell what is your OS?

On Windows 10 with this configuration and this example:

```
fun main() = Window {
    println("Window")
}
```

Window still calls only once.

**Comment by Omnieboer** [comment] 2021-02-26 15:13
Hi, I looked closer at the example and did some basic testing.
On Windows 10:
```kotlin
fun main() = Window {
    println("Window")
}
```
runs once, but
```kotlin
fun main() = Window {
    println("Window")
    MaterialTheme {
        println("Theme")
    }
}
```
gives:
Window
Theme
Theme

Theme twice

**Comment by igordmn** [comment] 2021-02-26 15:25
> what was happening in #86

There was another bug in TODO example in #86. It appears only if Window is called twice.
In #86 we forgot to wrap creation of object into `remember`. Without `remember` each recomposition will create a new object. With `remember` we will reuse object from the first composition.

>  I click in my app to add a line somewhere, and it appears for a moment before disappearing again.
Generally your Composable functions should work even if they called multiple times. Check your code, maybe somewhere `remember` is missing.

Only for performance reasons we need to reduce number of recompositions.

```
fun main() = Window {
    println("Window")
    MaterialTheme {
        println("Theme")
    }
}
```
This code also called once on my PC 🤔:
```
Window
Theme
```
Can you attach a zip archive with minimal reproducer? (and check if the issue appers if we run `gradlew run` in a terminal)

**Comment by Omnieboer** [comment] 2021-02-26 15:49
I will try to come back to you about this tomorrow, after some more testing. On the empty project I also get the correct print, once each. But I can't find a place that would call the UI again, and breakpoints don't seem to working at all in that project. I'll migrate it to a new project and see whether the problem persists.

**Comment by Omnieboer** [comment] 2021-03-02 14:25
Okay, I think I found the underlying mechanics for my problem, but I think it's working as intended, even though not as expected for me :P 
```kotlin
fun main() = Window {
    println("Window")
    val someNumber = remember { mutableStateOf(0.0) }
    MaterialTheme {
        println("Theme")
        Column {
            Button({ someNumber.value++ }) {
                Text("Click Me!")
            }
            Text("Clicked ${someNumber.value} times!") // <- This is important
        }
    }
}
```

If you don't have the "clicked x times" text field, and you keep clicking the button, the Theme is never called again. If you do have that Text there (i.e. if you read the value of `someNumber`), the program prints Theme again. Even if you replace the Text with a `println(someNumber.value)`, Theme is printed again for every click of the button.

Where I went wrong was not expecting a complete recompose for reading a value.

**Comment by Omnieboer** [comment] 2021-03-02 15:13
Interestingly, Theme isn't written more often when the reading happens at the same time as the button click:
```kotlin
fun main() = Window {
    println("Window")
    val someNumber = remember { mutableStateOf(0.0) }
    MaterialTheme {
        println("Theme")
        Column {
            Button({ someNumber.value++.also { println(it) } }) { 
                Text("Click Me!")
            }
//            Text("Clicked ${someNumber.value} times!")
//            println(someNumber.value)
        }
    }
}
```
Prints Theme once, no matter how many clicks

**Comment by okushnikov** [comment] 2024-08-26 17:42
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6464">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
