### ISSUE TITLE
Issue with transparency on Linux

### ISSUE THREAD

**Issue by DevSrSouza** [JetBrains/compose-jb#1339] opened 2021-10-31 22:18 UTC
I'm having couple issues with transparency support on Linux
- At my second monitor (4k one) it fails to setup SkiaLayer with a exception (in thread).
- When It get open at my primary monitor (2k) it have a poor performance, when I switch my second monitor to 2k the performance get a lot better. (the application is still being displayed at the first monitor)
- When I try to move the window to the second monitor (SUPER + SHIFT + LEFT) it gives my the exception in the first case and stop working.
- When moving from extend to mirror screens, the issue does not appear.
- When moving from single monitor to extend screen with the application is open, the issue do not appear.
- Using `WindowDraggableArea` also breaks the application if it was running previously.

System information:
- Pop!_OS 21.04 x86_64
- JDK 16
- Gnome version 3.38.5
- X11

Exception:
```
Cannot create Linux GL context
Exception in thread "AWT-EventQueue-0" java.lang.IllegalStateException: SkiaLayer is disposed
	at org.jetbrains.skiko.SkiaLayer.update$skiko(SkiaLayer.jvm.kt:408)
	at org.jetbrains.skiko.redrawer.AbstractDirectSoftwareRedrawer.redrawImmediately(AbstractDirectSoftwareRedrawer.kt:36)
	at org.jetbrains.skiko.redrawer.LinuxSoftwareRedrawer.redrawImmediately(LinuxSoftwareRedrawer.kt:24)
	at org.jetbrains.skiko.SkiaLayer.paint(SkiaLayer.jvm.kt:317)
	at androidx.compose.ui.awt.ComposeLayer$ComponentImpl.paint(ComposeLayer.desktop.kt:100)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
	at java.desktop/javax.swing.JLayeredPane.paint(JLayeredPane.java:586)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
	at java.desktop/javax.swing.JLayeredPane.paint(JLayeredPane.java:586)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
	at java.desktop/javax.swing.JComponent.paintToOffscreen(JComponent.java:5271)
	at java.desktop/javax.swing.BufferStrategyPaintManager.paint(BufferStrategyPaintManager.java:246)
	at java.desktop/javax.swing.RepaintManager.paint(RepaintManager.java:1323)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1060)
	at java.desktop/java.awt.GraphicsCallback$PaintCallback.run(GraphicsCallback.java:39)
	at java.desktop/sun.awt.SunGraphicsCallback.runOneComponent(SunGraphicsCallback.java:75)
	at java.desktop/sun.awt.SunGraphicsCallback.runComponents(SunGraphicsCallback.java:112)
	at java.desktop/java.awt.Container.paint(Container.java:2003)
	at java.desktop/java.awt.Window.paint(Window.java:3949)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:876)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:848)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:848)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:823)
	at java.desktop/javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:772)
	at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1884)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:316)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

Code
```
Window(
            onCloseRequest = ::exitApplication,
            undecorated = true,
            transparent = true,
            alwaysOnTop = true,
            resizable = false,
            state = windowState,
        ) {
            WindowDraggableArea {
                Surface(
                    modifier = Modifier.fillMaxSize().padding(8.dp).shadow(3.dp, RoundedCornerShape(20.dp)),
                    color = Color(55, 55, 55),
                    shape = RoundedCornerShape(20.dp) //window has round corners now
                ) {
                    Text("anything")
                }
            }
        }
```

**Comment by olonho** [comment] 2021-11-02 11:48
We need to document problem and workarounds.

**Comment by akurasov** [comment] 2021-11-02 15:38
idea is to document some workaround for application developers to mitigate this issue

**Comment by langara** [comment] 2021-11-09 08:36
I have the same exception when changing window state to WindowPlacement.Fullscreen
Happens iff Window(transparent = true, ...).
Even on single display (I checked both external and internal - no difference)
Ubuntu 21.10; Gnome 40.4.0; Wayland

**Comment by akurasov** [comment] 2021-11-15 15:35
Fix merged. Only documentation remains.

**Comment by DevSrSouza** [comment] 2021-11-15 16:08
Tested, is not crashing anymore, but transparency is not working at all now.

**Comment by DevSrSouza** [comment] 2021-11-15 16:14
Okay, is working but when happen the issue that would crash, the transparency is just disable.

**Closed** 2021-12-16 11:19 UTC
Labels: linux, window management, desktop, p:high, wait for test

**Comment by toasterofbread** [comment] 2024-02-16 14:33
I believe [this](https://bugs.openjdk.org/browse/JDK-8304900) (which is a transparency-specific duplicate of [this](https://bugs.openjdk.org/browse/JDK-8006421)) is the relevant bug in the JDK, which is marked as fixed in JDK 22.

I ran my project which exhibits this bug using the latest [build](https://jdk.java.net/22/) of JDK 22 and it did indeed fix the issue.

**Comment by okushnikov** [comment] 2024-07-14 15:55
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5205">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
