### ISSUE TITLE
App didn't start after packaging exe

### ISSUE THREAD

**Issue by memonahmedanees** [JetBrains/compose-jb#1108] opened 2021-08-25 08:31 UTC
When i add mysql connector jar lib to my project all things worked perfectly but after packaging app didn't open

**Comment by akurasov** [comment] 2021-08-25 11:26
Hello, what is you OS?

**Comment by akurasov** [comment] 2021-08-25 11:31
Duplicate of https://github.com/JetBrains/compose-jb/issues/1071

**Closed by akurasov** 2021-08-25 11:31 UTC
Labels: question, native distribution
