### ISSUE TITLE
unable to resize window, when undecorated is true (on windows)

### ISSUE THREAD

**Issue by Yofou** [JetBrains/compose-jb#520] opened 2021-03-19 19:21 UTC
title says the issue I've found, here's the code my window is using and a image of proof of this happening 
<https://i.gyazo.com/50e014aeaf6f309eb4851db37a3b5b82.mp4>

I've tested this on version 0.3.2 & 0.4.0-build174
```kt
fun main() = Window(
    title = "Cache Monkey",
    size = IntSize(1100, 635),
    undecorated = true,
    resizable = true,
) {
    MaterialTheme {
        Surface(
            color = Color(32, 32, 32),
            modifier = Modifier.fillMaxSize()
        ) {
            rememberRootComponent(factory = ::NavComponent).render()
        }
    }
}
```

**Comment by kirill-grouchnikov** [comment] 2021-03-19 19:29
See https://github.com/JetBrains/compose-jb/issues/178 - it's marked as "not a bug", but Compose for Desktop is still missing support for resizing undecorated windows.

**Comment by Yofou** [comment] 2021-03-19 19:31
> 
> 
> See #178 - it's marked as "not a bug", but Compose for Desktop is still missing support for resizing undecorated windows.

I think you're mistaking draggable for resizable, I'm already able to drag my undecorated window, with some help on the slack channel

**Comment by kirill-grouchnikov** [comment] 2021-03-19 19:32
That issue talks about both if you read all the comments

**Comment by Yofou** [comment] 2021-03-19 19:35
> 
> 
> That issue talks about both if you read all the comments

ah yeah, I was unable to delete my message before i realised 😓 haha
but yeah, that issue is a little outdated is seems as the new window api wasn't out yet?
also after talking on the slack channel it seems like at the very least it's not consistnet
behaviour across all OS's. for example while talking to apche on slack they showed they're
able to resize the window with undecorated turned on, on linux

**Comment by graycatdeveloper** [comment] 2021-05-08 10:19
```
import androidx.compose.desktop.AppWindow
import androidx.compose.ui.unit.IntSize
import java.awt.Color
import java.awt.Cursor
import java.awt.event.MouseEvent
import java.awt.event.MouseListener
import java.awt.event.MouseMotionListener
import java.lang.IllegalStateException
import javax.swing.BorderFactory
import javax.swing.JFrame

fun AppWindow.addUndecoratedWindowResizer(
	borderWidth: Int = 3,
	borderColor: Color = Color.BLACK,
	minSize: IntSize = IntSize(100, 100),
	maxSize: IntSize = IntSize(800, 600)
) {
	if (!window.isUndecorated)
		throw IllegalStateException("Window must be undecorated")
	UndecoratedWindowResizer(
		window,
		borderWidth,
		borderColor,
		minSize,
		maxSize
	)
}
internal class UndecoratedWindowResizer(
	private val frame: JFrame,
	private val borderWidth: Int,
	private val borderColor: Color,
	private val minSize: IntSize = IntSize(0, 0),
	private val maxSize: IntSize = IntSize(800, 600)
) : MouseListener, MouseMotionListener {
	
	private val border = BorderFactory.createEmptyBorder(
		borderWidth,
		borderWidth,
		borderWidth,
		borderWidth
	)
	
	private var cursorEvent = Cursor.DEFAULT_CURSOR
	
	init {
		frame.apply {
			rootPane.apply {
				background = borderColor
				border = this@UndecoratedWindowResizer.border
			}
			addMouseListener(this@UndecoratedWindowResizer)
			addMouseMotionListener(this@UndecoratedWindowResizer)
		}
	}
	
	private var frameX = frame.x
	private var frameY = frame.y
	private var frameWidth = frame.width
	private var frameHeight = frame.height
	
	override fun mousePressed(e: MouseEvent) {
		frameX = frame.location.x
		frameY = frame.location.y
		frameWidth = frame.width
		frameHeight = frame.height
	}
	
	override fun mouseMoved(e: MouseEvent) {
		val x = e.x
		val y = e.y
		val frameWidth = frame.width
		val frameHeight = frame.height
		cursorEvent = when {
			x < borderWidth && y < borderWidth -> Cursor.NW_RESIZE_CURSOR
			x < borderWidth && y > frameHeight - borderWidth -> Cursor.SW_RESIZE_CURSOR
			x > frameWidth - borderWidth && y < borderWidth -> Cursor.NE_RESIZE_CURSOR
			x > frameWidth - borderWidth && y > frameHeight - borderWidth -> Cursor.SE_RESIZE_CURSOR
			x < borderWidth -> Cursor.W_RESIZE_CURSOR
			x > frameWidth - borderWidth -> Cursor.E_RESIZE_CURSOR
			y < borderWidth -> Cursor.N_RESIZE_CURSOR
			y > frameHeight - borderWidth -> Cursor.S_RESIZE_CURSOR
			else -> Cursor.DEFAULT_CURSOR
		}
		setCursor(cursorEvent)
	}
	
	override fun mouseDragged(e: MouseEvent) {
		when (cursorEvent) {
			//LEFT
			Cursor.W_RESIZE_CURSOR -> {
				frame.setLocation(e.xOnScreen, frameY)
				val newWidth = frameWidth + frameX - e.xOnScreen
				setSize(width = newWidth)
			}
			//LEFT + TOP
			Cursor.NW_RESIZE_CURSOR -> {
				frame.setLocation(e.xOnScreen, e.yOnScreen)
				val newWidth = frameWidth + frameX - e.xOnScreen
				val newHeight = frameHeight + frameY - e.yOnScreen
				setSize(width = newWidth, height = newHeight)
			}
			//TOP
			Cursor.N_RESIZE_CURSOR -> {
				frame.setLocation(frameX, e.yOnScreen)
				val newHeight = frameHeight + frameY - e.yOnScreen
				setSize(height = newHeight)
			}
			//TOP + RIGHT
			Cursor.NE_RESIZE_CURSOR -> {
				frame.setLocation(frameX, e.yOnScreen)
				val newWidth = e.xOnScreen - frameX
				val newHeight = frameHeight + frameY - e.yOnScreen
				setSize(width = newWidth, height = newHeight)
			}
			//RIGHT
			Cursor.E_RESIZE_CURSOR -> {
				val newWidth = e.xOnScreen - frameX
				setSize(width = newWidth)
			}
			//RIGHT + BOTTOM
			Cursor.SE_RESIZE_CURSOR -> {
				val newWidth = e.xOnScreen - frameX
				val newHeight = e.yOnScreen - frameY
				setSize(width = newWidth, height = newHeight)
			}
			//BOTTOM
			Cursor.S_RESIZE_CURSOR -> {
				val newHeight = e.yOnScreen - frameY
				setSize(height = newHeight)
			}
			//LEFT + BOTTOM
			Cursor.SW_RESIZE_CURSOR -> {
				frame.setLocation(e.xOnScreen, frameY)
				val newWidth = frameWidth + frameX - e.xOnScreen
				val newHeight = e.yOnScreen - frameY
				setSize(width = newWidth, height = newHeight)
			}
		}
	}
	
	override fun mouseExited(e: MouseEvent) {
		setCursor(Cursor.DEFAULT_CURSOR)
	}
	
	override fun mouseClicked(e: MouseEvent) {
	}
	
	override fun mouseReleased(e: MouseEvent) {
	}
	
	override fun mouseEntered(e: MouseEvent) {
	}
	
	private fun setCursor(type: Int) {
		frame.cursor = Cursor(type)
	}
	
	private fun setSize(width: Int = frameWidth, height: Int = frameHeight) {
		val newWidth = width.coerceIn(minSize.width, maxSize.width)
		val newHeight = height.coerceIn(minSize.height, maxSize.height)
		frame.setSize(newWidth, newHeight)
	}
	
}

fun MainWindow(
	content: @Composable () -> Unit
) {
	SwingUtilities.invokeLater {
		val window = AppWindow(
			undecorated = true
		)
		window.addUndecoratedWindowResizer()
		window.show {
			content()
		}
	}
}

fun main() = MainWindow {
	//content
}
```

**Comment by akurasov** [comment] 2021-07-15 15:05
Duplicate of https://github.com/JetBrains/compose-jb/issues/178. It is not supported yet.

**Closed by akurasov** 2021-07-15 15:05 UTC
Labels: desktop, window management

**Comment by okushnikov** [comment] 2024-07-14 17:32
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5475">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
