### ISSUE TITLE
Preview like in Android Studio?

### ISSUE THREAD

**Issue by GGorAA** [JetBrains/compose-jb#174] opened 2020-12-07 13:35 UTC
As in the title, when the preview functionality (like in Android Studio Canary) will appear in Compose for Desktop?

**Comment by olonho** [comment] 2020-12-08 06:32
Duplicate of https://github.com/JetBrains/compose-jb/issues/136, please avoid creating duplicated issues.

**Closed by olonho** 2020-12-08 06:32 UTC
Labels: enhancement, ide

**Comment by okushnikov** [comment] 2024-08-26 17:44
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6510">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
