### ISSUE TITLE
Canvas.drawArc is ignoring size parameter

### ISSUE THREAD

**Issue by rustamsmax** [JetBrains/compose-jb#458] opened 2021-03-02 06:57 UTC
`Canvas.drawArc` is ignoring `size` parameter
The issue is specific to desktop app.
Android app is working as expected.

![image](https://user-images.githubusercontent.com/36570577/109610280-5f366d00-7b4e-11eb-884f-5554597983a9.png)

A workaround was to draw path with `Path.addArcRad`

![image](https://user-images.githubusercontent.com/36570577/109610309-66f61180-7b4e-11eb-8c61-9debe0ac41be.png)

**Comment by olonho** [comment] 2021-03-02 07:06
Could you please provide code snippet that manifests bad behavior?
Also note that signature of `drawArc` is 
```kotlin
fun drawArc(
        left: Float,
        top: Float,
        right: Float,
        bottom: Float,
        startAngle: Float,
        sweepAngle: Float,
        useCenter: Boolean,
        paint: Paint
    )
```
and doesn't have `size` parameter.

**Comment by rustamsmax** [comment] 2021-03-02 07:08
I used second function

![image](https://user-images.githubusercontent.com/36570577/109611408-010a8980-7b50-11eb-995b-720402777c0c.png)

**Comment by rustamsmax** [comment] 2021-03-02 07:09
I used second option

![image](https://user-images.githubusercontent.com/36570577/109611471-154e8680-7b50-11eb-98cc-87059a60cc7b.png)

**Comment by olonho** [comment] 2021-03-02 07:14
Which version of Compose is that? Don't see method with such signature in 0.3.1 or 0.3.2.

**Comment by olonho** [comment] 2021-03-02 07:15
Is it actually `DrawScope.drawArc`?

**Comment by olonho** [comment] 2021-03-02 07:33
Works for me with code like that:
```kotlin
val infiniteTransition = rememberInfiniteTransition()
    val radius by infiniteTransition.animateFloat(
        initialValue = 1f,
        targetValue = 600f,
        animationSpec = infiniteRepeatable(
            animation = tween(5000),
            repeatMode = RepeatMode.Restart
        )
    )
    Canvas(modifier = Modifier.fillMaxSize()) {
            drawArc(
                color = Color.Black, topLeft = Offset.Zero, size = Size(radius, radius),
                startAngle = 0f, sweepAngle = -180f, useCenter = false,
                style = Stroke(width = 1f), alpha = 1.0f
            )
    }
```

**Comment by rustamsmax** [comment] 2021-03-02 08:17
I'm using 0.4.0-build168
I'm not animating radius. I'm sharing full code snippet

https://gist.github.com/rustamsmax/a8083c6c3f330b18f8d4673052d33f1e

**Comment by olonho** [comment] 2021-03-02 09:27
Indeed, we use Skija 
```java
public Canvas drawArc(float left, float top, float width, float height, float startAngle, float sweepAngle, boolean includeCenter, @NotNull Paint paint)
`
as 
```kotlin
verride fun drawArc(
        left: Float,
        top: Float,
        right: Float,
        bottom: Float,
        startAngle: Float,
        sweepAngle: Float,
        useCenter: Boolean,
        paint: Paint
    ) {
        skija.drawArc(
            left,
            top,
            right,
            bottom,
            startAngle,
            sweepAngle,
            useCenter,
            paint.skija
        )
    }
`

**Comment by prepor** [comment] 2021-03-02 09:45
Thank you for the report! The fix is on the go! :)

**Comment by olonho** [comment] 2021-03-05 07:46
Should be fixed in `0.4.0-build171`, please check.

**Comment by rustamsmax** [comment] 2021-03-05 20:04
Still not fixed

**Comment by LouisCAD** [comment] 2021-03-07 13:28
@rustamsmax Sharing a reproducer that can be copy pasted (not a screenshot) should help maintainers check it's fixed 😉.

**Comment by prepor** [comment] 2021-03-09 09:23
@rustamsmax I've just checked with `0.4.0-build173` and it looks like this:

<img width="315" alt="Screenshot 2021-03-09 at 10 22 07" src="https://user-images.githubusercontent.com/2827/110448382-71ba2480-80c1-11eb-9e82-d50c42d55c64.png">

It looks correct, right?

**Comment by rustamsmax** [comment] 2021-03-09 20:57
Hi @prepor Yes exactly. Did you uncomment the drawArc function call? In the code snippet the drawPath was a workaround

**Comment by prepor** [comment] 2021-03-11 07:10
@rustamsmax yes, I did :)

**Comment by olonho** [comment] 2021-03-15 06:06
@rustamsmax so does it fix it for you?

**Comment by timo-drick** [comment] 2021-03-17 04:18
Not sure if it is related to this but i noticed that drawArc works not as expected when you define an offset. In this case it behaves differently. E.g. to get an Arc in center i have to use following code:
Tested on 0.4.0-build171
`Kotlin
fun main() = Window {
    Canvas(Modifier.fillMaxSize()) {
        val d = size.minDimension
        val r = d / 2f
        val offset = Offset((size.width / 2f - r), size.height / 2f - r)
        drawArc(
            color = Color.Green,
            size = Size(d - offset.x, d - offset.y), //  minus offset.x/y is the workaround and is not necessary in Android.
            topLeft = offset,
            startAngle = -90f,
            sweepAngle = 270f,
            useCenter = true
        )
    }
}
`

**Comment by timo-drick** [comment] 2021-03-17 04:19
Ok it is fixed in build: 0.4.0-build173
:+1:

**Comment by akurasov** [comment] 2021-07-16 12:41
Closing, as it is fixed.

**Closed by akurasov** 2021-07-16 12:41 UTC
Labels: bug, rendering

**Comment by okushnikov** [comment] 2024-08-26 17:39
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6375">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
