### ISSUE TITLE
Declaring multiple fonts in fontFamily leads to Compose using only the first declared

### ISSUE THREAD

**Issue by GGorAA** [JetBrains/compose-jb#171] opened 2020-12-05 22:36 UTC
I am creating my custom theme, and fonts are broken in Compose. Here is my declaration of fontFamily:

```Kotlin
val Montserrat = fontFamily(
        font(
            "Montserrat SemiBold",
            "font/montserrat/semibold.ttf",
            FontWeight.SemiBold,
            FontStyle.Normal
        ),
        font(
            "Montserrat Black",
            "font/montserrat/black.ttf",
            FontWeight.Black,
            FontStyle.Normal
        ),
        font(
            "Montserrat Black Italic",
            "font/montserrat/blackitalic.ttf",
            FontWeight.Black,
            FontStyle.Italic
        ),
        font(
            "Montserrat Bold",
            "font/montserrat/bold.ttf",
            FontWeight.Bold,
            FontStyle.Normal
        ),
        font(
            "Montserrat Bold Italic",
            "font/montserrat/bolditalic.ttf",
            FontWeight.Bold,
            FontStyle.Italic
        ),
        font(
            "Montserrat Extra Bold",
            "font/montserrat/extrabold.ttf",
            FontWeight.ExtraBold,
            FontStyle.Normal
        )
        // and a lot, lot more fonts...
)
```

Notice that the first declared font is SemiBold.

Than I applied some styling to text:

```Kotlin
val MyTypography = Typography(
        h4 = TextStyle(
            fontFamily = Montserrat,
            fontWeight = FontWeight.Normal,
            fontSize = 30.sp
        ),
        h5 = TextStyle(
            fontFamily = Montserrat,
            fontWeight = FontWeight.Black,
            fontSize = 24.sp
        ),
        h6 = TextStyle(
            fontFamily = Montserrat,
            fontWeight = FontWeight.Normal,
            fontSize = 20.sp
        ),
        subtitle1 = TextStyle(
            fontFamily = Montserrat,
            fontWeight = FontWeight.Normal,
            fontSize = 16.sp
        ),
        subtitle2 = TextStyle(
            fontFamily = Montserrat,
            fontWeight = FontWeight.Normal,
            fontSize = 14.sp
        )
        // Some more text styles...
    )
```

Notice that font weight everywhere in that styling is set to `Normal`. Only in `h5` it is set to `Black`, but that doesn't matter.

But, the font weight applied to every `Text` is - you guessed it - `SemiBold`.

![image](https://user-images.githubusercontent.com/61655029/101266770-e09e7f00-375a-11eb-82cb-5376b211f4ee.png)

I think it is a bug, not me screwing something up again :D

Sorry if I screwed some English grammar in this report :D

**Comment by prepor** [comment] 2020-12-08 15:06
`Typography` overwrites `fontFamily` part of provided textstyles by `defaultFontFamily`. Please, try to pass `Montserrat` as `defaultFontFamily`

**Comment by GGorAA** [comment] 2020-12-08 17:40
![image](https://user-images.githubusercontent.com/61655029/101520486-3eb2a880-398d-11eb-8021-5978fc91e211.png)
Am I doing something wrong?

**Comment by GGorAA** [comment] 2020-12-08 18:01
Yes, I am doing something wrong. I am passing this argument in the wrong place. I fond where I need to place it :D

**Comment by GGorAA** [comment] 2020-12-08 18:03
Aaaaaaaaand nope, not worked. It still does not applies the fontWeight.

**Comment by prepor** [comment] 2020-12-08 18:58
Ok, then could you please provide a complete executable example to reproduce a problem, including how are you using defined Typography. Because locally it's working for me with my local fonts

**Comment by prepor** [comment] 2020-12-08 19:05
When I say "executable" I mean "compilable" :)

**Comment by GGorAA** [comment] 2020-12-09 10:55
I can give you the actual project for you to test out. And here it is:

[Engine-GUI-Client.zip](https://github.com/JetBrains/compose-jb/files/5665362/Engine-GUI-Client.zip)

**Comment by rock3r** [comment] 2020-12-13 10:08
I'm seeing the exact same issue @prepor — ping me on Slack/Space if you need more details :)

**Comment by Chozzle** [comment] 2021-01-23 04:06
This seems to be fixed in latest build141 🚀

**Comment by CarsonRedeye** [comment] 2021-01-25 10:44
MacOS 11.1

**Comment by prepor** [comment] 2021-01-26 16:17
@GGorAA  could you please try it with 0.3.0-build143? Please, feel free to reopen this issue if the problem is still here

**Closed by prepor** 2021-01-26 16:17 UTC
Labels: bug

**Comment by okushnikov** [comment] 2024-08-26 17:43
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6487">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
