### ISSUE TITLE
onClick event listener for tray icon

### ISSUE THREAD

**Issue by bqliang** [JetBrains/compose-jb#1898] opened 2022-02-25 07:22 UTC
> onAction - Action performed when user clicks on the tray icon (double click on Windows, right click on macOS)

Hope can add onClick event listener foe tray icon. Although Tray has the onAction parameter, but sometimes it's not very useful. For example, on Window platform, I close the program window, but the tray icon is still on the taskbar, I hope make the window redisplay by left click it. (not double-click). 

Click is more logical than double-click to redisplay window, At least on the window platform.

**Comment by alexfacciorusso** [comment] 2022-10-26 12:14
Isn't this a duplicate of https://github.com/JetBrains/compose-jb/issues/290 ?

**Comment by igordmn** [comment] 2022-10-26 12:20
Yes, let's keep only https://github.com/JetBrains/compose-jb/issues/290

**Closed by igordmn** 2022-10-26 12:20 UTC
Labels: enhancement, desktop

**Comment by okushnikov** [comment] 2024-08-26 15:51
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1898">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
