### ISSUE TITLE
Is there a good webview solution for jb?

### ISSUE THREAD

**Issue by fendo8888** [JetBrains/compose-jb#1622] opened 2021-12-20 10:17 UTC
Based on the implementation of chrome or Firefox, although currently swing has jcef and javafx has webview, can jb provide a webview component similar to electron? The main reason is that the compatibility of the two is not very optimistic.

**Comment by akurasov** [comment] 2021-12-20 11:01
At the moment no. You could try to use some Swing WebView solution via Compose-Swing interop

**Comment by akurasov** [comment] 2021-12-20 11:03
Duplicate of https://github.com/JetBrains/compose-jb/issues/668

**Closed by akurasov** 2021-12-20 11:03 UTC

**Comment by KevinnZou** [comment] 2023-11-09 01:27
I would recommend this library https://github.com/KevinnZou/compose-webview-multiplatform. It supports WebView on the desktop side using JCEF.

**Comment by okushnikov** [comment] 2024-07-14 16:09
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5109">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
