### ISSUE TITLE
Support `isSystemInDarkTheme()`

### ISSUE THREAD

**Issue by ColtonIdle** [JetBrains/compose-jb#755] opened 2021-06-05 14:06 UTC
For my project that I'm converting from android compose to jetbrains compose, I created a theme that is basically a replica of the "jetsnack" compose sample app. https://github.com/android/compose-samples/tree/main/Jetsnack/app/src/main/java/com/example/jetsnack/ui/theme

But in Theme.kt `isSystemInDarkTheme` does not compile on desktop. import androidx.compose.foundation.isSystemInDarkTheme

**Comment by smallshen** [comment] 2021-06-09 13:34
https://github.com/Dansoftowner/jSystemThemeDetector
this may work

**Comment by akurasov** [comment] 2021-07-20 12:39
Closing, as it is a duplicate of https://github.com/JetBrains/compose-jb/issues/169. 
BTW, it already works on MacOs and Windows.

**Closed by akurasov** 2021-07-20 12:39 UTC
Labels: api change

**Comment by okushnikov** [comment] 2024-08-26 17:38
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6358">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
