### ISSUE TITLE
OutlinedTextField Error

### ISSUE THREAD

**Issue by liushengGitHub** [JetBrains/compose-jb#180] opened 2020-12-09 14:58 UTC
When typing, print event.text must not be null
code
`fun main() = Window(undecorated = true,) {
    Box(Modifier.drawLayer(translationX = 100f)) {
        var value by remember { mutableStateOf("") }
        OutlinedTextField(value, { value = it })
    }
}`
print
`
SkIcuLoader: datafile missing: C:\Program Files\Java\jdk-11\bin\icudtl.dat.
DesktopPlatformInput.showSoftwareKeyboard
Exception in thread "AWT-EventQueue-0 @coroutine#1" java.lang.NullPointerException: event.text must not be null
	at androidx.compose.ui.platform.DesktopPlatformInput.onInputMethodTextChanged(DesktopPlatformInput.kt:163)
	at androidx.compose.ui.platform.DesktopOwners.onInputMethodTextChanged(DesktopOwners.kt:160)
	at androidx.compose.desktop.ComposeLayer$initCanvas$1$inputMethodTextChanged$1.invoke(ComposeLayer.kt:149)
	at androidx.compose.desktop.ComposeLayer$initCanvas$1$inputMethodTextChanged$1.invoke(ComposeLayer.kt)
	at androidx.compose.desktop.AWTDebounceEventQueue$job$1.invokeSuspend(AWTDebounceEventQueue.kt:58)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
`

**Comment by GGorAA** [comment] 2020-12-09 17:34
Duplicate of #170

**Comment by GGorAA** [comment] 2020-12-09 17:54
I'll help someone that will read this report. Here is the code above:

```Kotlin
fun main() = Window(undecorated = true) {
    Box(
        Modifier.
            drawLayer(translationX = 100f)
    ) { 
    var value by remember { mutableStateOf("") }

    OutlinedTextField(
        value,
        { value = it }
    )

    }
}
```

And the print:

```
SkIcuLoader: datafile missing: C:\Program Files\Java\jdk-11\bin\icudtl.dat. DesktopPlatformInput.showSoftwareKeyboard Exception in thread "AWT-EventQueue-0 @coroutine#1" java.lang.NullPointerException: event.text must not be null at androidx.compose.ui.platform.DesktopPlatformInput.onInputMethodTextChanged(DesktopPlatformInput.kt:163) at androidx.compose.ui.platform.DesktopOwners.onInputMethodTextChanged(DesktopOwners.kt:160) at androidx.compose.desktop.ComposeLayer$initCanvas$1$inputMethodTextChanged$1.invoke(ComposeLayer.kt:149) at androidx.compose.desktop.ComposeLayer$initCanvas$1$inputMethodTextChanged$1.invoke(ComposeLayer.kt) at androidx.compose.desktop.AWTDebounceEventQueue$job$1.invokeSuspend(AWTDebounceEventQueue.kt:58) at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313) at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770) at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721) at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715) at java.base/java.security.AccessController.doPrivileged(Native Method) at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740) at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113) at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109) at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by spkingr** [comment] 2021-01-14 08:04
What's the data file of `icudtl.dat`:
"SkIcuLoader: datafile missing: C:\Program Files\Java\jdk-11\bin\icudtl.dat."
I have the same problem, hope it fixes for jdk-11.

**Comment by akurasov** [comment] 2021-07-15 15:16
works fine for me now on JDK-15. The only change is to replace Modifier.drawLayer with Modifier.graphicsLayer. Does anyone has this issue?

**Comment by akurasov** [comment] 2021-09-17 11:50
Issue is not reproducible on latest builds

**Closed by akurasov** 2021-09-17 11:50 UTC
Labels: desktop

**Comment by okushnikov** [comment] 2024-08-26 17:36
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6294">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
