### ISSUE TITLE
java.lang.IllegalArgumentException: Anchor refers to a group that was removed

### ISSUE THREAD

**Issue by gbaldeck** [JetBrains/compose-jb#345] opened 2021-02-03 14:23 UTC
It seems that issue https://github.com/JetBrains/compose-jb/issues/199 has come up again in the last several builds (146-148).

One difference that I noticed between the behavior I'm experiencing and that of https://github.com/JetBrains/compose-jb/issues/199, is that the exception is only thrown when I edit a text box on the dialog, then close the dialog.

One thing to mention about this bug is that it does make the calling window unusable when it happens. Clicks do not work anymore and there are odd graphical issues when you do click. So right now, if you use a dialog for anything more than an OK/Cancel dialog (like adding some text boxes) then it breaks the window that opened the dialog.

**Comment by jimgoog** [comment] 2021-02-03 16:41
When you say "last several builds", can you provide exact build numbers?  This is useful to remove ambiguity (sometimes users claim to be on latest but actually aren't) and also for the future when people are looking through issues and won't necessarily know which builds were latest back in early February 2021.

**Comment by gbaldeck** [comment] 2021-02-03 17:00
I discovered it in build 146 and it still exists in 148.

**Comment by arkivanov** [comment] 2021-02-11 22:11
Same here. Can give a reproducer if needed.

**Comment by arkivanov** [comment] 2021-02-11 22:53
So the error exactly occurs when I edit a field in a `Dialog` or in a `Popup` and then dismiss:

```
Exception in thread "AWT-EventQueue-0 @coroutine#2" java.lang.ArrayIndexOutOfBoundsException: Index -2 out of bounds for length 10240
	at androidx.compose.runtime.SlotTableKt.groupSize(SlotTable.kt:2559)
	at androidx.compose.runtime.SlotTableKt.access$groupSize(SlotTable.kt:1)
	at androidx.compose.runtime.SlotReader.groupSize(SlotTable.kt:596)
	at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(Composer.kt:2217)
	at androidx.compose.runtime.ComposerImpl.skipCurrentGroup(Composer.kt:2501)
	at androidx.compose.runtime.ComposerImpl.recompose$runtime(Composer.kt:2627)
	at androidx.compose.runtime.CompositionImpl.recompose(Composition.kt:267)
	at androidx.compose.runtime.Recomposer.performRecompose(Recomposer.kt:555)
	at androidx.compose.runtime.Recomposer.access$performRecompose(Recomposer.kt:96)
	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$4.invoke(Recomposer.kt:448)
	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$4.invoke(Recomposer.kt:422)
	at androidx.compose.runtime.BroadcastFrameClock$FrameAwaiter.resume(BroadcastFrameClock.kt:41)
	at androidx.compose.runtime.BroadcastFrameClock.sendFrame(BroadcastFrameClock.kt:62)
	at androidx.compose.ui.platform.DesktopOwners.onFrame(DesktopOwners.kt:108)
	at androidx.compose.desktop.ComposeLayer$1.onRender(ComposeLayer.kt:123)
	at org.jetbrains.skiko.SkiaLayer.update$skiko(SkiaLayer.kt:91)
	at org.jetbrains.skiko.redrawer.LinuxOpenGLRedrawer.update(LinuxOpenGLRedrawer.kt:46)
	at org.jetbrains.skiko.redrawer.LinuxOpenGLRedrawer.access$update(LinuxOpenGLRedrawer.kt:13)
	at org.jetbrains.skiko.redrawer.LinuxOpenGLRedrawer$Companion$frameDispatcher$1.invokeSuspend(LinuxOpenGLRedrawer.kt:67)
	at org.jetbrains.skiko.redrawer.LinuxOpenGLRedrawer$Companion$frameDispatcher$1.invoke(LinuxOpenGLRedrawer.kt)
	at org.jetbrains.skiko.FrameDispatcher$job$1.invokeSuspend(FrameDispatcher.kt:32)
	(Coroutine boundary)
	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2.invokeSuspend(Recomposer.kt:422)
	at androidx.compose.ui.platform.DesktopOwners$2.invokeSuspend(DesktopOwners.kt:78)
	(Coroutine creation stacktrace)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:186)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
	at androidx.compose.ui.platform.DesktopOwners.<init>(DesktopOwners.kt:77)
	at androidx.compose.desktop.ComposeLayer.<init>(ComposeLayer.kt:59)
	at androidx.compose.desktop.ComposeWindow.<init>(ComposeWindow.kt:33)
	at androidx.compose.desktop.AppWindow.<init>(AppWindow.kt:110)
	at androidx.compose.desktop.AppWindow.<init>(AppWindow.kt)
	at androidx.compose.desktop.AppWindowKt$Window$1.run(AppWindow.kt:79)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:316)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index -2 out of bounds for length 10240
	at androidx.compose.runtime.SlotTableKt.groupSize(SlotTable.kt:2559)
	at androidx.compose.runtime.SlotTableKt.access$groupSize(SlotTable.kt:1)
	at androidx.compose.runtime.SlotReader.groupSize(SlotTable.kt:596)
	at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(Composer.kt:2217)
	at androidx.compose.runtime.ComposerImpl.skipCurrentGroup(Composer.kt:2501)
	at androidx.compose.runtime.ComposerImpl.recompose$runtime(Composer.kt:2627)
	at androidx.compose.runtime.CompositionImpl.recompose(Composition.kt:267)
	at androidx.compose.runtime.Recomposer.performRecompose(Recomposer.kt:555)
	at androidx.compose.runtime.Recomposer.access$performRecompose(Recomposer.kt:96)
	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$4.invoke(Recomposer.kt:448)
	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$4.invoke(Recomposer.kt:422)
	at androidx.compose.runtime.BroadcastFrameClock$FrameAwaiter.resume(BroadcastFrameClock.kt:41)
	at androidx.compose.runtime.BroadcastFrameClock.sendFrame(BroadcastFrameClock.kt:62)
	at androidx.compose.ui.platform.DesktopOwners.onFrame(DesktopOwners.kt:108)
	at androidx.compose.desktop.ComposeLayer$1.onRender(ComposeLayer.kt:123)
	at org.jetbrains.skiko.SkiaLayer.update$skiko(SkiaLayer.kt:91)
	at org.jetbrains.skiko.redrawer.LinuxOpenGLRedrawer.update(LinuxOpenGLRedrawer.kt:46)
	at org.jetbrains.skiko.redrawer.LinuxOpenGLRedrawer.access$update(LinuxOpenGLRedrawer.kt:13)
	at org.jetbrains.skiko.redrawer.LinuxOpenGLRedrawer$Companion$frameDispatcher$1.invokeSuspend(LinuxOpenGLRedrawer.kt:67)
	at org.jetbrains.skiko.redrawer.LinuxOpenGLRedrawer$Companion$frameDispatcher$1.invoke(LinuxOpenGLRedrawer.kt)
	at org.jetbrains.skiko.FrameDispatcher$job$1.invokeSuspend(FrameDispatcher.kt:32)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	... 13 more
```

**Comment by deepakgahlot98** [comment] 2021-02-22 04:49
After updating to Jetpack compose Alpha-12, and kotlin version to 1.4.30. While closing the dialog I'm facing this issue.

```
2021-02-22 10:14:16.294 26670-26670/com.***.*****.mint E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.sap.ariba.mint, PID: 26670
    java.lang.IllegalArgumentException: Anchor refers to a group that was removed
        at androidx.compose.runtime.SlotTable.anchorIndex(SlotTable.kt:199)
        at androidx.compose.runtime.Anchor.toIndexFor(SlotTable.kt:466)
        at androidx.compose.runtime.ComposerImpl$CompositionContextImpl.getCompositionLocalScope$runtime_release(Composer.kt:3124)
        at androidx.compose.runtime.ComposerImpl.startRoot(Composer.kt:1140)
        at androidx.compose.runtime.ComposerImpl.recompose$runtime_release(Composer.kt:2697)
        at androidx.compose.runtime.CompositionImpl.recompose(Composition.kt:306)
        at androidx.compose.runtime.Recomposer.performRecompose(Recomposer.kt:533)
        at androidx.compose.runtime.Recomposer.access$performRecompose(Recomposer.kt:95)
        at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$4.invoke(Recomposer.kt:423)
        at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$4.invoke(Recomposer.kt:397)
        at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.kt:34)
        at androidx.compose.ui.platform.AndroidUiDispatcher.performFrameDispatch(AndroidUiDispatcher.kt:112)
        at androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch(AndroidUiDispatcher.kt:43)
        at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.kt:72)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:909)
        at android.view.Choreographer.doCallbacks(Choreographer.java:723)
        at android.view.Choreographer.doFrame(Choreographer.java:655)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6944)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```

**Comment by deepakgahlot98** [comment] 2021-02-22 04:51
This refers to the same issue. 
Looks like it is fixed.

**Comment by nobleminsu** [comment] 2021-03-01 08:29
Also reproduced in the build 145, 
`Exception in thread "AWT-EventQueue-0 @coroutine#3" java.lang.IllegalArgumentException: Anchor refers to a group that was removed
	at androidx.compose.runtime.SlotTable.anchorIndex(SlotTable.kt:199)
	at androidx.compose.runtime.Anchor.toIndexFor(SlotTable.kt:466)
	at androidx.compose.runtime.ComposerImpl$CompositionReferenceImpl.getAmbientScope$runtime(Composer.kt:3104)
	at androidx.compose.runtime.ComposerImpl.startRoot(Composer.kt:1133)
	at androidx.compose.runtime.ComposerImpl.recompose$runtime(Composer.kt:2678)
	at androidx.compose.runtime.CompositionImpl.recompose(Composition.kt:306)
	at androidx.compose.runtime.Recomposer.performRecompose(Recomposer.kt:480)
	at androidx.compose.runtime.Recomposer.access$performRecompose(Recomposer.kt)
	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$4.invoke(Recomposer.kt:393)
	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$4.invoke(Recomposer.kt)
	at androidx.compose.runtime.ActualDesktopKt$DefaultMonotonicFrameClock$2$1.withFrameNanos(ActualDesktop.kt:110)
	at androidx.compose.runtime.ActualDesktopKt$DefaultMonotonicFrameClock$2$1$withFrameNanos$1.invokeSuspend(ActualDesktop.kt)
	(Coroutine boundary)
	at androidx.compose.ui.platform.WrapperKt$GlobalDefaultRecomposer$1$1$1.invokeSuspend(Wrapper.kt:62)
	(Coroutine creation stacktrace)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:186)
	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source)
	at androidx.compose.ui.platform.WrapperKt.<clinit>(Wrapper.kt:61)
	at androidx.compose.desktop.ComposeLayer.initOwner(ComposeLayer.kt:247)
	at androidx.compose.desktop.ComposeLayer.access$initOwner(ComposeLayer.kt)
	at androidx.compose.desktop.ComposeLayer$Wrapped.init(ComposeLayer.kt:75)
	at org.jetbrains.skiko.HardwareLayer.checkIsShowing(HardwareLayer.kt:30)
	at org.jetbrains.skiko.HardwareLayer.access$checkIsShowing(HardwareLayer.kt:7)
	at org.jetbrains.skiko.HardwareLayer$1.hierarchyChanged(HardwareLayer.kt:22)
	at java.desktop/java.awt.Component.processHierarchyEvent(Component.java:6781)
	at java.desktop/java.awt.Component.processEvent(Component.java:6400)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4990)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4822)
	at java.desktop/java.awt.Component.createHierarchyEvents(Component.java:5628)
	at java.desktop/java.awt.Container.createHierarchyEvents(Container.java:1466)
	at java.desktop/java.awt.Container.createHierarchyEvents(Container.java:1466)
	at java.desktop/java.awt.Container.createHierarchyEvents(Container.java:1466)
	at java.desktop/java.awt.Container.createHierarchyEvents(Container.java:1466)
	at java.desktop/java.awt.Component.show(Component.java:1680)
	at java.desktop/java.awt.Window.show(Window.java:1056)
	at java.desktop/java.awt.Component.show(Component.java:1717)
	at java.desktop/java.awt.Component.setVisible(Component.java:1664)
	at java.desktop/java.awt.Window.setVisible(Window.java:1028)
	at androidx.compose.desktop.ComposeWindow.setVisible(ComposeWindow.kt:54)
	at androidx.compose.desktop.AppWindow.show(AppWindow.kt:435)
	at androidx.compose.desktop.AppWindow.show$default(AppWindow.kt:421)
	at MainKt$main$1.run(main.kt:40)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:316)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)`

**Comment by sol-digital** [comment] 2021-03-02 07:06
Have same problem in 1.0.0-beta01. Have FATAL EXCEPTION while closing the dialog after edit TextField or OutlinedTextField.

**Comment by js-bonin** [comment] 2021-03-03 14:58
Same issue here in a DialogFragment on 1.0.0-beta01 kotlin 1.4.31

`java.lang.ArrayIndexOutOfBoundsException: length=10240; index=-2
        at androidx.compose.runtime.SlotTableKt.groupSize(SlotTable.kt:2558)
        at androidx.compose.runtime.SlotTableKt.access$groupSize(SlotTable.kt:1)
        at androidx.compose.runtime.SlotReader.groupSize(SlotTable.kt:596)
        at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(Composer.kt:2215)
        at androidx.compose.runtime.ComposerImpl.skipCurrentGroup(Composer.kt:2499)
        at androidx.compose.runtime.ComposerImpl.recompose$runtime_release(Composer.kt:2625)
        at androidx.compose.runtime.CompositionImpl.recompose(Composition.kt:406)
        at androidx.compose.runtime.Recomposer.performRecompose(Recomposer.kt:724)
        at androidx.compose.runtime.Recomposer.access$performRecompose(Recomposer.kt:100)
        at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:437)
        at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:411)
        at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:34)
        at androidx.compose.ui.platform.AndroidUiDispatcher.performFrameDispatch(AndroidUiDispatcher.android.kt:112)
        at androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch(AndroidUiDispatcher.android.kt:43)
        at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:72)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:970)
        at android.view.Choreographer.doCallbacks(Choreographer.java:796)
        at android.view.Choreographer.doFrame(Choreographer.java:727)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7660)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)`

Any workaround?

**Comment by sol-digital** [comment] 2021-03-03 15:04
> Same issue here in a DialogFragment on 1.0.0-beta01 kotlin 1.4.31
> 
> ```
> java.lang.ArrayIndexOutOfBoundsException: length=10240; index=-2
>         at androidx.compose.runtime.SlotTableKt.groupSize(SlotTable.kt:2558)
>         at androidx.compose.runtime.SlotTableKt.access$groupSize(SlotTable.kt:1)
>         at androidx.compose.runtime.SlotReader.groupSize(SlotTable.kt:596)
>         at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(Composer.kt:2215)
>         at androidx.compose.runtime.ComposerImpl.skipCurrentGroup(Composer.kt:2499)
>         at androidx.compose.runtime.ComposerImpl.recompose$runtime_release(Composer.kt:2625)
>         at androidx.compose.runtime.CompositionImpl.recompose(Composition.kt:406)
>         at androidx.compose.runtime.Recomposer.performRecompose(Recomposer.kt:724)
>         at androidx.compose.runtime.Recomposer.access$performRecompose(Recomposer.kt:100)
>         at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:437)
>         at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:411)
>         at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:34)
>         at androidx.compose.ui.platform.AndroidUiDispatcher.performFrameDispatch(AndroidUiDispatcher.android.kt:112)
>         at androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch(AndroidUiDispatcher.android.kt:43)
>         at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:72)
>         at android.view.Choreographer$CallbackRecord.run(Choreographer.java:970)
>         at android.view.Choreographer.doCallbacks(Choreographer.java:796)
>         at android.view.Choreographer.doFrame(Choreographer.java:727)
>         at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
>         at android.os.Handler.handleCallback(Handler.java:938)
>         at android.os.Handler.dispatchMessage(Handler.java:99)
>         at android.os.Looper.loop(Looper.java:223)
>         at android.app.ActivityThread.main(ActivityThread.java:7660)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
> ```
> 
> Any workaround?

As stated at the beginning of this thread, the exception is thrown only if the TextField inside the Dialog is focused on closing. The crash can be avoided by disabling the TextField (setting the enabled parameter to false) right before closing/hiding the Dialog.

**Comment by sol-digital** [comment] 2021-03-09 09:07
Feb 26, 2021 09:42AM
Marked as fixed.
https://issuetracker.google.com/issues/180124293

So waiting the 1.0.0-beta02.

**Comment by arkivanov** [comment] 2021-05-16 13:08
Works fine for me, verified on `0.4.0-build190`

**Comment by igordmn** [comment] 2021-07-06 16:15
Closing, since the issue has been fixed. Let us know if it still exists.

**Closed by igordmn** 2021-07-06 16:15 UTC

**Comment by okushnikov** [comment] 2024-08-26 17:40
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6399">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
