### ISSUE TITLE
HorizontalScrollbar in combination with LazyRow calculates wrong width of scrollbar

### ISSUE THREAD

**Issue by brolicious12** [JetBrains/compose-jb#1368] opened 2021-11-06 14:56 UTC
This is a possible bug in HorizontalScrollbar/(untested VerticalScrollbar) only if u pass LazyListState.
The width of the scrollbar shrinks while scrolling.
If i use Modifier.horizontalScroll the scrollbar does not change width while scrolling.

I would expect that the same width can always be expected in both cases.

`id("org.jetbrains.kotlin.jvm") version ("1.5.30")`
`id("org.jetbrains.compose") version ("1.0.0-alpha4-build344")`
`window 10 desktop`

```

import androidx.compose.foundation.HorizontalScrollbar
import androidx.compose.foundation.horizontalScroll
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.lazy.LazyRow
import androidx.compose.foundation.lazy.rememberLazyListState
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.rememberScrollbarAdapter
import androidx.compose.material.Text
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import androidx.compose.ui.window.singleWindowApplication

fun main() = singleWindowApplication {
	val lls = rememberLazyListState()
	val ss = rememberScrollState()
	
	Column(modifier = Modifier.fillMaxWidth()) {
		Row(modifier = Modifier.horizontalScroll(ss)) {
			for (i in 0..150)
				Text("item$i")
		}
		HorizontalScrollbar(modifier = Modifier.fillMaxWidth(),
		                    adapter = rememberScrollbarAdapter(ss))
		
		Spacer(modifier = Modifier.height(10.dp))
		
		LazyRow(state = lls,
		        modifier = Modifier.fillMaxWidth()) {
			for (i in 0..150)
				item { Text("item$i") }
		}
		HorizontalScrollbar(modifier = Modifier.fillMaxWidth(),
		                    adapter = rememberScrollbarAdapter(lls))
	}
}

```

![scrollbarbug](https://user-images.githubusercontent.com/89709434/140613965-fd54c2fd-5d85-4022-9c73-bf9224d6419d.PNG)

**Comment by igordmn** [comment] 2021-11-08 11:30
It is not a bug, it is a feature :).

Because of the nature of LazyRow (we measure/layout only visible items), we can't know the whole scrollable content width. So, we have to approximate it by the current visible items.

Because of the approximation, we have a different scrollbar width.

**Comment by igordmn** [comment] 2021-11-20 00:09
Closing, as it is works as intended, and probably impossible to calculate the width precisely

**Closed by igordmn** 2021-11-20 00:09 UTC
Labels: question, desktop

**Comment by okushnikov** [comment] 2024-08-26 16:10
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6212">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
