### ISSUE TITLE
TextField. Wrong rendering of the cursor at the end of the line

### ISSUE THREAD

**Issue by YaPravaATyNet** [JetBrains/compose-jb#1214] opened 2021-09-30 09:01 UTC
<img width="850" alt="Screenshot 2021-09-30 at 11 50 50" src="https://user-images.githubusercontent.com/41040018/135421536-85465940-a8ae-444c-af73-ca6bf427cbf1.png">

I run notepad example and try to put the cursor at the end of the second line

**Comment by christoph-grimm** [comment] 2021-09-30 19:54
I can confirm that issue in the textfield editing; versions since alpha4-331. 

cursor and writing positions seem to get out of sync (Mac OS, M1)

**Comment by prepor** [comment] 2021-11-02 10:33
Should be fixed by https://android-review.googlesource.com/c/platform/frameworks/support/+/1878317
waiting for a merge

**Comment by prepor** [comment] 2021-11-02 10:39
@christoph-grimm @YaPravaATyNet thank you for the detailed report!

**Comment by christoph-grimm** [comment] 2021-11-11 17:48
Still there in beta6-dev455

Easier reproducer: 

Add line 1 with content "asdf". 
Add line 2 with content "asdfj".
Press cursor up. 
Type ... The cursor does not move up and remains in line 2. The added text appears in line 1. 

Seems to have the issue generally for line n, n+1 with length(line n+1 ) >= length(line n): 
Cursor cannot be positioned behind last character in situation as above.

**Comment by akurasov** [comment] 2021-11-16 09:20
Yes, works fine in this version

**Closed by akurasov** 2021-11-16 09:20 UTC
Labels: bug, desktop, p:critical, wait for test

**Comment by okushnikov** [comment] 2024-07-14 17:29
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5238">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
