### ISSUE TITLE
Compiler plugin doesn't pass/affect value to `val` constructor property when there is a @Composable lambda as another property

### ISSUE THREAD

**Issue by ylemoigne** [JetBrains/compose-jb#1052] opened 2021-08-13 17:59 UTC
Using Kotlin 1.5.21, and compose-jb 1.0.0-alpha3 (Same behavior tested with 0.0.0-SNAPSHOT (0.0.0-20210812.153519-19))
Using JS IR Compiler

The following code :
```kotlin
import androidx.compose.runtime.*

data class Break(val myValue:String, val renderer:@Composable ()->Any?){
    init {
        println(myValue)
    }
}

class AlsoBreak(val myValue:String, val renderer:@Composable ()->Any?){
    init {
        println(myValue)
    }
}

data class Works(val myValue:String, val renderer:()->Any?){
    init {
        println(myValue)
    }
}


fun main(){
    Works("works", {})
    Break("break", {})
    AlsoBreak("alsoBreak", {})
}
```

Produce :
```
works
undefined
undefined
```

**Comment by hfhbd** [comment] 2021-08-13 18:45
Duplicate of https://github.com/JetBrains/compose-jb/issues/746

**Comment by eymar** [comment] 2021-09-15 10:25
fixed. added new test cases: https://github.com/JetBrains/compose-jb/blob/master/web/compose-compiler-integration/src/jsTest/kotlin/ComposablesInConstructorTests.kt

**Closed by eymar** 2021-09-15 10:25 UTC
Labels: web

**Comment by okushnikov** [comment] 2024-07-14 17:36
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5305">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
