### ISSUE TITLE
Double click slows down onClick trigger

### ISSUE THREAD

**Issue by pyricau** [JetBrains/compose-jb#255] opened 2021-01-07 18:10 UTC
Setting a `onDoubleClick` callback on the clickable modifier delays the time at which `onClick` is called for the same element. Example code:

```kotlin
Row(
  modifier = Modifier
    .wrapContentHeight()
    .clickable(
      onClick = {
        // Update UI
      },
      onDoubleClick = {
        //
      }
    )
)
```

This is likely implemented so that a double click is not mistaken for a click, i.e. the listener waits for the double click time threshold before firing the onclick. While understandable, this also makes the UI response noticeably slower and creates perceived lag.

**Comment by pyricau** [comment] 2021-01-07 18:15
One work around here is to  simply not use onDoubleClick at all, and use timestamps with consecutive onClick calls.

**Comment by jimgoog** [comment] 2021-01-08 13:08
This is a tricky one.  Waiting ~300ms for double-click is fairly standard practice, and it is one of the reasons that modern web browsers suggest avoiding double click behaviors and removed tap-to-zoom from mobile web apps (https://developers.google.com/web/updates/2013/12/300ms-tap-delay-gone-away)

The workaround you suggested seems like the most pragmatic solution to me, as it punts the detection problem to user land where the developer is able to make more informed decisions about how to respond to a single click that is then discovered to be a part of a double click.  We should probably expose a way for you to query what is the expected double-click timeout on the current platform, since users can change that for accessibility reasons.

@pyricau Can you please file this bug against Compose?  https://b.corp.google.com/issues/new?component=612128&template=1253476 - as this clickable modifier API contract is provided on the Compose side and should be reviewed/changed there.  I'm not sure if we have an actionable solution to this though; do you have any ideas on what a better behavior would be?  If so, can you please include those in the bug?

**Comment by ruckustboom** [comment] 2021-01-08 15:20
> Waiting ~300ms for double-click is fairly standard practice

Are you sure about that? I don't believe I've never seen a framework or platform that doesn't also report single clicks when a double click handler is present.

**Comment by jimgoog** [comment] 2021-01-08 15:47
From the first sentence of the [previous page](https://developers.google.com/web/updates/2013/12/300ms-tap-delay-gone-away) I linked:
> For many years, mobile browsers applied a 300-350ms delay between touchend and click while they waited to see if this was going to be a double-tap or not, since double-tap was a gesture to zoom into text.

I know this was true on Chrome, Firefox, IE, etc.  And I feel like I've heard about the same thing being done on other platforms.  And I know for most gestures, a gesture is not fired until it is disambiguated among all other gestures in the arena.  Although I'll admit I haven't done a formal survey of precisely which frameworks/platforms do what, and from doing a couple of quick google searches it's a bit hard to tell how prevalent this is (waiting vs. firing singleClick right away).  I can actually see a pretty valid argument for why single click should be fired even before a double-click fires, but then that opens the question of "should single click fire again when the double click fires" because now you're always firing the first half of the double click gesture but only firing the second half if the double click gesture is not installed.  ¯\_(ツ)_/¯

I don't feel strongly, I just want to do whatever will be most useful for developers.  I suppose the thing Android did is have a gesture detector with different handlers for singleTap and singleTapConfirmed, perhaps that's the way to go.  ¯\_(ツ)_/¯

**Comment by ruckustboom** [comment] 2021-01-08 18:35
Indeed, but that seems to imply it's a thing of the past, whereas your comment made it sound more like an ongoing issue. Granted, my experience is quite limited and it is definitely possible I'm falling prey to selection bias.

Personally, I'm a fan of how the click handling is done with JavaFX. Every time you click, an event is fired, and that event includes a click count, telling you how many times this click has been repeated. That makes it easy for the user to decide if they want to handle single and double clicks, wait some time for a second click, wait till the 478th click, etc.

**Comment by olonho** [comment] 2021-01-11 10:18
True, however it requires serious rework of core Compose APIs.

**Comment by olonho** [comment] 2021-01-13 09:56
Practically speaking, we likely mark this bug as "won't fix", until further work in Core Compose affecting it will take place.

**Closed by olonho** 2021-01-13 09:56 UTC
Labels: api change, enhancement

**Comment by jimgoog** [comment] 2021-01-13 10:02
FWIW, I think you can do the following to get the fast click and double-click behavior:

```
.clickable(onClick = {...})
.clickable(onDoubleClick = {...})
```

If that doesn't work, please file a bug in Compose Core / upstream.

**Comment by pyricau** [comment] 2021-01-19 20:50
Filed https://issuetracker.google.com/issues/177929160 to track the core compose issues.

I agree with most of the points here, yet I think this is a core API design issue that will confuse developers, so something needs to be done. I tried to outline those details in the issue.

**Comment by pyricau** [comment] 2021-01-19 21:49
> FWIW, I think you can do the following to get the fast click and double-click behavior:
> 
> ```
> .clickable(onClick = {...})
> .clickable(onDoubleClick = {...})
> ```
> 

This doesn't work, single clicks are ignored (note that onClick is not nullable so that second method call needs `onClick = {}`)

**Comment by bennysway** [comment] 2023-01-09 02:39
Managed to get a better workaround

```kotlin
.onClick(
    interactionSource = interactionSource,
    onDoubleClick = {
        // Do something
    }
){}
.onPointerEvent(PointerEventType.Press) { /* Do something else */  }
```

Not sure how stable/practical it is, but on single fire events, it passed my stress tests

**Comment by okushnikov** [comment] 2024-07-14 16:21
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5555">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
