### ISSUE TITLE
AlertDialog shape not correctly applied (Surface has its own shape)

### ISSUE THREAD

**Issue by quentin23soleil** [JetBrains/compose-jb#1705] opened 2022-01-17 18:12 UTC
JB-Compose 1.0.1 as well as latest alpha `1.1.0-alpha1-dev550`. 

Related to [this slack message](https://kotlinlang.slack.com/archives/C01D6HTPATV/p1642402133147100)

`Surface` has a RectangleShape which is not overridden by `AlertDialog` resulting of a `MaterialTheme.colors.surface` rectangle shaped background (grey in the screenshot).

(sorry for the colours 👀 )
![image](https://user-images.githubusercontent.com/1037667/149819878-fd30ccba-cc0b-465f-87c1-7074c8731fbc.png)

**Comment by akurasov** [comment] 2022-01-18 16:55
Could you share a small reproducer for it, please? Better with not so bright colors )

**Comment by quentin23soleil** [comment] 2022-01-18 18:29
Sure, any AlertDialog with a shape will reproduce the issue.


```
        AlertDialog(
            backgroundColor = Color.Green,
            contentColor = Color.Red,
            shape = RoundedCornerShape(16.dp),
            onDismissRequest = {},
            buttons = {
                Button(
                    onClick = {},
                    content = {
                        Text("Ok")
                    })
            },
            title = { Text("Error") },
            text = { Text("Hello alert dialog") }
        )
```

**Comment by dragossusi** [comment] 2022-01-26 12:14
This always happens to me on desktop, on android it works correctly

**Comment by ScottPierce** [comment] 2022-01-26 14:57
My team is encountering this as well.

**Comment by dima-avdeev-jb** [comment] 2022-11-29 06:44
Reproduce in this repository:
https://github.com/dima-avdeev-jb/reproduce-bug-with-alert-dialog

**Comment by sproctor** [comment] 2022-12-28 09:26
This is a duplicate of #1269.

**Comment by dima-avdeev-jb** [comment] 2022-12-28 10:48
Duplicate of https://github.com/JetBrains/compose-jb/issues/1269

**Closed by dima-avdeev-jb** 2022-12-28 10:48 UTC
Labels: duplicate

**Comment by okushnikov** [comment] 2024-08-26 15:49
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1705">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
