### ISSUE TITLE
Modifiers clickable and toggleable don't fire if there's a delay between down and up mouse events

### ISSUE THREAD

**Issue by kirill-grouchnikov** [JetBrains/compose-jb#140] opened 2020-11-25 13:57 UTC
```
@Composable
fun Thing(
    modifier: Modifier = Modifier,
    interactionState: InteractionState = remember { InteractionState() },
    content: @Composable RowScope.() -> Unit
) {
    val selected = remember{ mutableStateOf(false)}
    Box(
        modifier = modifier
            .background(if (selected.value) Color.Green else Color.Red)
            .pointerMoveFilter(
                onEnter = {
                    println("Entered")
                    false
                },
                onExit = {
                    println("Exited")
                    false
                },
                onMove = {
                    false
                })
            .toggleable(
                value = selected.value,
                enabled = true,
                interactionState = interactionState,
                indication = null,
                onValueChange = {
                    println("Toggled!")
                    selected.value = !selected.value
                })
    ) {
        Row(
            Modifier
                .defaultMinSizeConstraints(
                    minWidth = 64.dp,
                    minHeight = 36.dp
                )
                .padding(8.dp),
            horizontalArrangement = Arrangement.Center,
            verticalAlignment = Alignment.CenterVertically,
            content = content
        )
    }
}

fun main() = Window {
    Column(modifier = Modifier.fillMaxHeight().fillMaxWidth()) {
        Thing() {
            Text("sample")
        }
    }
}
```

If `pointerMoveFilter` is removed, "long" toggling works. But the combination of the two makes long toggle (mouse down, wait a second, mouse up) not working

**Comment by kirill-grouchnikov** [comment] 2020-11-25 13:57
This is macOS + build129

**Comment by olonho** [comment] 2020-12-08 06:53
@kirill-grouchnikov could you please specify what exact behaviour do you expect?

**Comment by kirill-grouchnikov** [comment] 2020-12-08 07:03
It shouldn't matter how much time passes between down and up events. This is how pretty much all native apps on my Mac work.

**Comment by igordmn** [comment] 2020-12-08 08:20
It looks like a bug, long toggling should work, no matter if we use pointerMoveFilter or not

**Comment by akurasov** [comment] 2021-07-23 09:19
MacOs + build265 works fine (adjusted reproducer to API changes). @kirill-grouchnikov is it reproducible on your system now?

```
@Composable

fun Thing(
    modifier: Modifier = Modifier,
    content: @Composable RowScope.() -> Unit
) {
    val selected = remember{ mutableStateOf(false)}
    Box(
        modifier = modifier
            .background(if (selected.value) Color.Green else Color.Red)
            .pointerMoveFilter(
                onEnter = {
                    false
                },
                onExit = {
                    false
                },
                onMove = {
                    false
                })
            .toggleable(
                value = selected.value,
                enabled = true,
                interactionSource = remember { MutableInteractionSource() },
                indication = null,
                onValueChange = {
                    println("Toggled!")
                    selected.value = !selected.value
                })
    ) {
        Row(
            Modifier
                .defaultMinSize(
                    minWidth = 64.dp,
                    minHeight = 36.dp
                )
                .padding(8.dp),
            horizontalArrangement = Arrangement.Center,
            verticalAlignment = Alignment.CenterVertically,
            content = content
        )
    }
}
```

**Comment by kirill-grouchnikov** [comment] 2021-07-23 15:10
Yes, this is working on 265 now

**Comment by akurasov** [comment] 2021-07-23 15:14
Closing then

**Closed by akurasov** 2021-07-23 15:14 UTC
Labels: AK, bug, desktop, discussion, input

**Comment by okushnikov** [comment] 2024-07-14 17:39
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5593">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
