### ISSUE TITLE
Touchscreen scroll not supported!

### ISSUE THREAD

**Issue by Richyeoh** [JetBrains/compose-jb#1557] opened 2021-12-07 12:01 UTC
```kotlin
Box {
    val stateVertical = rememberScrollState(0)
    val data = (0 until 1000).map { "Item $it" }
    Column(modifier = Modifier.verticalScroll(stateVertical)) {
        for (i in data) {
            Text(
                i,
                Modifier
                    .padding(14.dp)
                    .fillMaxWidth()
            )
        }
    }
    VerticalScrollbar(
        modifier = Modifier.align(Alignment.CenterEnd)
            .fillMaxHeight(),
        adapter = rememberScrollbarAdapter(stateVertical),
    )
}
```
or 
```kotlin
val data = (0 until 1000).map { "Item $it" }
LazyColumn {
  items(data) { i ->
      Text(
          i,
          Modifier
              .padding(14.dp)
              .fillMaxWidth()
      )
  }
}
```
Not support touchscreen scroll.

Who can help me, thank you.

**Comment by akurasov** [comment] 2021-12-07 12:46
Duplicate of #1555

**Closed by akurasov** 2021-12-07 12:46 UTC

**Comment by okushnikov** [comment] 2024-08-26 16:08
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6184">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
