### ISSUE TITLE
[Windows] NOT VM - RuntimeException : Can't wrap nullptr

### ISSUE THREAD

**Issue by ypujante** [JetBrains/compose-jb#317] opened 2021-01-25 17:00 UTC
I am opening the exact same issue as https://github.com/JetBrains/compose-jb/issues/125 because I was asked to do so on the slack forum. So the problem is the exact same one but it is not due to running in a VM this time.

I am running on a physical Windows 10 machine (Windows 10 pro, 24GB). 

```
Host Name:                 HAF932
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.18363 N/A Build 18363
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          Yan
Registered Organization:
Original Install Date:     7/27/2019, 7:34:10 AM
System Boot Time:          1/24/2021, 11:41:05 AM
System Manufacturer:       System manufacturer
System Model:              System Product Name
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 42 Stepping 7 GenuineIntel ~3401 Mhz
BIOS Version:              American Megatrends Inc. 3603, 11/9/2012
Windows Directory:         C:\WINDOWS
System Directory:          C:\WINDOWS\system32
Boot Device:               \Device\HarddiskVolume1
System Locale:             en-us;English (United States)
Input Locale:              en-us;English (United States)
Time Zone:                 (UTC-08:00) Pacific Time (US & Canada)
Total Physical Memory:     24,543 MB
Available Physical Memory: 19,747 MB
Virtual Memory: Max Size:  49,119 MB
Virtual Memory: Available: 42,901 MB
Virtual Memory: In Use:    6,218 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    WORKGROUP
```

I am using java 15:

```
java version "15.0.2" 2021-01-19
Java(TM) SE Runtime Environment (build 15.0.2+7-27)
Java HotSpot(TM) 64-Bit Server VM (build 15.0.2+7-27, mixed mode, sharing)
```

I am using the latest version of compose-jb

```
plugins {
    kotlin("jvm") version "1.4.21"
    id("org.jetbrains.compose") version "0.3.0-build141"
}
```

on the unmodified code generated by IDEA 2020.3 

```
IntelliJ IDEA 2020.3.1 (Ultimate Edition)
Build #IU-203.6682.168, built on December 29, 2020
Runtime version: 11.0.9.1+11-b1145.63 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.14.6
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Non-Bundled Plugins: com.tang, org.jetbrains.plugins.hocon, org.jetbrains.kotlin, Pythonid
```

The behavior is the following:

Running `./gradlew.bat run` generates the following error:

```
> Task :run
SkIcuLoader: datafile missing: C:\Program Files\Java\jdk-15.0.2\bin\icudtl.dat.
Exception in thread "AWT-EventQueue-0" java.lang.RuntimeException: Can't wrap nullptr
        at org.jetbrains.skija.impl.Native.<init>(Native.java:13)
        at org.jetbrains.skija.impl.Managed.<init>(Managed.java:15)
        at org.jetbrains.skija.impl.Managed.<init>(Managed.java:11)
        at org.jetbrains.skija.impl.RefCnt.<init>(RefCnt.java:8)
        at org.jetbrains.skija.DirectContext.<init>(DirectContext.java:26)
        at org.jetbrains.skiko.RenderTargetsKt.makeGLContext(RenderTargets.kt:6)
        at org.jetbrains.skiko.SkiaLayer.draw(SkiaLayer.kt:57)
        at org.jetbrains.skiko.HardwareLayer.redrawLayer(Native Method)
        at androidx.compose.desktop.ComposeLayer.onFrame(ComposeLayer.kt:77)
        at androidx.compose.desktop.ComposeLayer$onFrame$1.invokeSuspend(ComposeLayer.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:316)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

The actual error is `Can't wrap nullptr` and it is assumed it is due to the previous line `SkIcuLoader: datafile missing: C:\Program Files\Java\jdk-15.0.2\bin\icudtl.dat` but that is just an assumption.

Also because I have been asked, yes OpenGL is installed on my machine.

**Comment by olonho** [comment] 2021-01-26 06:05
Once we'll implement DirectX rendering, it could help with issues like this one.

**Comment by knk190001** [comment] 2021-01-27 02:56
I just ran into the same issue after disabling my IGPU.

**Comment by olonho** [comment] 2021-01-28 10:50
We're working on getting software rasterizer fallback for such cases.

**Comment by Fabian-K** [comment] 2021-01-31 16:28
Does that mean this issue occurs when some prerequisite is not met/installed on the machine? If yes, what´s that?

**Comment by jimgoog** [comment] 2021-01-31 17:25
Yes, we currently assume that OpenGL is properly configured on the machine to provide hardware accelerated graphics.  Most machines have this configured properly already because it is generally provided by your graphics drivers, but some (especially virtual machines) don't, which is thought to be the root cause of this issue and where a software fallback could help fill the gap.

**Comment by jimgoog** [comment] 2021-01-31 17:28
Yes, we currently assume that OpenGL is properly configured on the machine to provide hardware accelerated graphics. Most machines have this configured properly already because it is generally provided by your graphics drivers, but some (especially virtual machines) don't, which is thought to be the root cause of this issue and where a software fallback could help fill the gap.

So to answer your question: Ensuring you have OpenGL installed, enabled, and properly running is the current prerequisite.

**Comment by ypujante** [comment] 2021-01-31 18:09
That being said, the issue is `java.lang.RuntimeException: Can't wrap nullptr` and I think because of the warning message, right now the assumption is being made that it is an OpenGL issue. It might be the case, but are we 100% sure it is?

I am **not** running a VM and OpenGL is properly installed on my machine. I personally don't know how to "Ensuring you have OpenGL installed, enabled, and properly running" more than what I have done.

**Comment by jimgoog** [comment] 2021-01-31 18:54
Normally the only way to verify is to run a GPU benchmark (my favorite was `glxgears`, but that was a decade ago and is a Linux-only benchmark).  I might consider trying something like https://www.geeks3d.com/gputest/ - although I have no idea what "good" and "bad" numbers would be nowadays.  You might compare to another machine where Compose for Desktop works (and thus OpenGL is known to be working), and see if the numbers are in the same ballpark.

@ypujante It's a little hard for us to debug without being able to reproduce on our own machines, but if you're not afraid of C++ and are willing to do a bit of digging for us... I'm assuming the issue is that skia's `GrContext::MakeGL(...)` is returning a `NULL` pointer.  You could try compiling one of the skia GPU examples (eg. https://skia.org/user/api/skcanvas_creation#gpu) from the GPU section of the skia docs, and play with it until you get that function to return a working (non-NULL) context, and that would help us understand what's going on here.

**Comment by ypujante** [comment] 2021-01-31 18:58
@jimgoog I don't promise anything but if I have time I will take a look

**Comment by ypujante** [comment] 2021-02-01 01:21
My PC uses a NVidia GTX970 and I tried to upgrade the drivers to the most recent version. After the upgrade the exception is gone! The warning message is **not** (which I think validates the point I was making that the warning and the exception might not be necessarily linked).

I do not understand why upgrading to the latest version of the NVidia drivers fixed this issue. It's not like there was no drivers installed.. they were just old...

So if you want to close this issue, it is up to you. I don't know why there is a warning message and if that will trigger some other error down the line, but the issue of the exception preventing the (very simplistic one button) app from working has been resolved by simply installing the latest NVidia drivers...

**Comment by jimgoog** [comment] 2021-02-01 01:49
The warning (I assume you are referring to `SkIcuLoader: datafile missing: C:\Program Files\Java\jdk-15.0.2\bin\icudtl.dat.`, let me know if you mean something else) is not what we were looking at.  I'm not 100% sure, but if I had to speculate, ICU is referring to "International Components for Unicode" and it is basically saying it couldn't find some sort of data file for text shaping/rendering.  Which is fine, I think it would fall back to some reasonable default.  This is a completely unrelated issue though.

The exception is what lead us to think that OpenGL was not working correctly.  The fact that upgrading your graphics driver fixed the problem more-or-less confirms this hypothesis.  Once we implement DirectX rendering and a software rasterizer fallback, this should do better in situations where users don't have their OpenGL / graphics chips setup properly.

**Comment by olonho** [comment] 2021-02-02 06:43
ICU message is an unrelated warning, and shall go away with recent Skiko. We implemented software (i.e. slower) fallback if OpenGL based rendering is not available. Also DirectX support for Windows machine is being developed.

**Comment by olonho** [comment] 2021-02-21 15:21
Please check with 0.3.0-rc1.

**Comment by akurasov** [comment] 2021-07-16 09:23
@ypujante do you still have this issue with the any recent Compose MP build?

**Comment by ypujante** [comment] 2021-07-16 12:24
I have not tried a recent version of Compose MP on Windows nor do I have the opportunity at this time.

**Comment by akurasov** [comment] 2021-09-17 13:04
Tried latest compose build on windows 10 and faced no issues. Closing this one.

**Closed by akurasov** 2021-09-17 13:04 UTC
Labels: bug, rendering, desktop

**Comment by okushnikov** [comment] 2024-08-26 17:36
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6291">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
