### ISSUE TITLE
svg image not working

### ISSUE THREAD

**Issue by shaokeyibb** [JetBrains/compose-jb#1028] opened 2021-08-08 12:35 UTC
```Kotlin
Icon(
            painter = svgResource("logo.svg"),
            contentDescription = "Logo",
            modifier = Modifier.size(100.dp)
        )
```

I use these code to show a svg image,but it seem appear as a full-black image,and no error here

**Comment by WWALKINGG** [comment] 2021-08-09 01:28
试试其他svg图呢？

**Comment by shaokeyibb** [comment] 2021-08-09 01:56
> 试试其他svg图呢？

依然不可以，似乎显示了图片轮廓，但图片为全黑
(Still not,seems to appear the outline of the image,but content is still full-black)
![image](https://user-images.githubusercontent.com/25865657/128653390-d6c92a62-b9ef-4ecb-abcb-f0e514e92921.png)

**Comment by WWALKINGG** [comment] 2021-08-09 06:56
无法复现

**Comment by shaokeyibb** [comment] 2021-08-09 08:41
> 无法复现

我的 JDK 版本是 16，在 11 下测试也不行
（My JDK Version is 16,and also failed on JDK 11)

**Comment by akurasov** [comment] 2021-08-09 08:46
can you also share you logo.svg?

**Comment by shaokeyibb** [comment] 2021-08-09 09:47
> can you also share you logo.svg?

i tried to use many of image,but they are all failed, one of them [here](https://drive.google.com/file/d/1c-VDfaE46G0HPXYZtgjOeW-A7m9xq33N/view?usp=sharing)

and MaterialTheme configuration
```Kotlin
MaterialTheme(
            colors = lightColors(
                Color(40, 181, 244),
                Color(114, 231, 255),
                Color(124, 179, 66),
                Color(174, 229, 113),
                error = Color(244, 67, 54)
            )
        )
```

**Comment by akurasov** [comment] 2021-11-03 08:54
Currently we do not support svg files with CSS. This is Skia limitation - it is used to load such files. 

This issue as a duplicate of https://github.com/JetBrains/compose-jb/issues/1217

**Closed by akurasov** 2021-11-03 08:54 UTC
Labels: question, desktop, Saved

**Comment by okushnikov** [comment] 2024-07-14 17:31
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5320">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
