### ISSUE TITLE
Slider does't allow next elements in a row to be displayed

### ISSUE THREAD

**Issue by bassstorm** [JetBrains/compose-jb#1765] opened 2022-01-29 15:36 UTC
Any element in a row after slider gets effectively zero space.
Not 100% sure, but seems that's what also mentioned in #1484 comments. 
Effective on `compose-jb` 1.0.1.

In below example, second button isn't visible at all.
```
@Composable
@Preview
fun TestSlider() {
    Box {
        Row {
            Button(
                onClick = {

                }
            ) {
                Text("Process")
            }
            Slider(
                value = 0f,
                valueRange = 0f..1f,
                onValueChange = {

                },
            )
            Button(
                onClick = {

                }
            ) {
                Text("Terminate")
            }
        }
    }
}
```

![Slider](https://user-images.githubusercontent.com/749825/151666951-ec10b358-e926-468c-871f-9a92f0957f13.png)

**Comment by akurasov** [comment] 2022-01-31 11:50
Reproduced. Same problem on Android. Should be reported to Google

**Comment by akurasov** [comment] 2022-01-31 11:53
https://issuetracker.corp.google.com/issues/216912877

**Comment by bassstorm** [comment] 2022-02-05 13:15
Thank you!
Unfortunately I cannot access above link, but hopefully updates will fly timely :)

**Comment by akurasov** [comment] 2022-02-11 15:53
Seems to be fixed in https://partnerissuetracker.corp.google.com/issues/210289161

**Comment by igordmn** [comment] 2022-02-14 16:21
You need to add:

```
Slider(
    value = 0f,
    valueRange = 0f..1f,
    onValueChange = {

    },
    modifier = Modifier.weight(1f)
)
```

see explanation [here](https://issuetracker.google.com/issues/216912877#comment2)

**Closed by igordmn** 2022-02-14 16:21 UTC
Labels: bug, google

**Comment by okushnikov** [comment] 2024-07-14 17:21
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1765">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
