### ISSUE TITLE
LazyRowFor does not work as expected.

### ISSUE THREAD

**Issue by iwahara** [JetBrains/compose-jb#168] opened 2020-12-04 16:42 UTC
kotlin ver. : 1.4.20
compose ver.: 0.3.0-build133

![lazyrow_scroll](https://user-images.githubusercontent.com/3982522/101189755-cdc47580-369a-11eb-8474-fa3a0e6e65aa.gif)

Reproduction code:

```kotlin
import androidx.compose.desktop.DesktopMaterialTheme
import androidx.compose.desktop.Window
import androidx.compose.foundation.ExperimentalFoundationApi
import androidx.compose.foundation.HorizontalScrollbar
import androidx.compose.foundation.border
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyRowFor
import androidx.compose.foundation.lazy.rememberLazyListState
import androidx.compose.foundation.rememberScrollbarAdapter
import androidx.compose.material.MaterialTheme
import androidx.compose.material.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp

@ExperimentalFoundationApi
fun main() = Window {

    DesktopMaterialTheme {
        Box(modifier = Modifier.fillMaxSize().padding(10.dp)) {
            val stateHorizontal = rememberLazyListState()

            val cols = (0..30).toList()

            Column {
                LazyRowFor(items = cols, state = stateHorizontal) { c ->
                    Box(
                        modifier = Modifier.border(width = 1.dp, color = MaterialTheme.colors.onBackground)
                            .preferredSize(80.dp, 20.dp)
                    ) {
                        Text("data_${c}")
                    }
                }
                LazyRowFor(items = cols, state = stateHorizontal) { c ->
                    Box(
                        modifier = Modifier.border(width = 1.dp, color = MaterialTheme.colors.onBackground)
                            .preferredSize(80.dp, 20.dp)
                    ) {
                        Text("data_${c}")
                    }
                }
            }

            HorizontalScrollbar(
                modifier = Modifier.align(Alignment.BottomStart).fillMaxWidth(),
                adapter = rememberScrollbarAdapter(
                    scrollState = stateHorizontal,
                    itemCount = cols.size,
                    averageItemSize = 80.dp
                )
            )
        }

    }
}
```

**Comment by igordmn** [comment] 2020-12-04 17:06
Thanks!

On Android it is also reproduced:

```
import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.compose.foundation.border
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.preferredSize
import androidx.compose.foundation.lazy.LazyRowFor
import androidx.compose.foundation.lazy.rememberLazyListState
import androidx.compose.material.MaterialTheme
import androidx.compose.material.Text
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.setContent
import androidx.compose.ui.unit.dp
import kotlinx.coroutines.delay

class DemoActivity : ComponentActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContent {
            Box(modifier = Modifier.fillMaxSize().padding(10.dp)) {
                val stateHorizontal = rememberLazyListState()

                val cols = (0..30).toList()

                Column {
                    LazyRowFor(items = cols, state = stateHorizontal) { c ->
                        Box(
                            modifier = Modifier.border(width = 1.dp, color = MaterialTheme.colors.onBackground)
                                .preferredSize(80.dp, 20.dp)
                        ) {
                            Text("data_${c}")
                        }
                    }
                    LazyRowFor(items = cols, state = stateHorizontal) { c ->
                        Box(
                            modifier = Modifier.border(width = 1.dp, color = MaterialTheme.colors.onBackground)
                                .preferredSize(80.dp, 20.dp)
                        ) {
                            Text("data_${c}")
                        }
                    }
                }

                LaunchedEffect(Unit) {
                    delay(2000)
                    stateHorizontal.snapToItemIndex(3, 0)
                }
            }
        }
    }
}
```

**Comment by GGorAA** [comment] 2020-12-07 09:34
If it is also reproduced on Android, it means that it is a core issue of Compose, not a problem of a Desktop one.

**Comment by iwahara** [comment] 2020-12-07 12:10
I see. Thanks!
I'll take a look at IssueTracker on Android for now, and if there is no Issue, I'll add it.

I'll leave this Issue open for now.

**Comment by akurasov** [comment] 2021-07-23 13:57
It seems to be the same on Android. Created a ticket about it - https://partnerissuetracker.corp.google.com/issues/194464779

**Comment by akurasov** [comment] 2021-08-02 08:56
According to Google team this is desired behavior - each list should have their own scrollable state. They are going to add check to throw exceptions in such cases. Closing this ticket.

**Closed by akurasov** 2021-08-02 08:56 UTC
Labels: bug, desktop, google, scroll

**Comment by okushnikov** [comment] 2024-08-26 17:38
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6343">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
