### ISSUE TITLE
Use of java.awt.MouseInfo.getPointerInfo in headless environment no longer working

### ISSUE THREAD

**Issue by jamesreprise** [JetBrains/compose-jb#2398] opened 2022-10-13 08:38 UTC
Using compose library version 1.1.0-alpha04, we are able to make use of the below function in a headless environment. However, after bumping to 1.2.0, we encouter this error:

```
java.awt.HeadlessException: 
No X11 DISPLAY variable was set, but this program performed an operation which requires it.
at java.desktop/java.awt.MouseInfo.getPointerInfo(MouseInfo.java:76)
```

Being able to test our application in a headless CI environment is an important part of our workflow and should be a common mode of operation in my mind.

Setting dummy display values (i.e. `export DISPLAY=:0`) was unsuccessful. We are able to run the tests on our local machines (with displays).

This occurs using kotlinc 1.7.20, Compose Compiler 1.3.2, Compose libraries with all versions on 1.2.0, skiko 0.7.34.

Let us know if we can provide you with any more information. Many thanks.

**Comment by igordmn** [comment] 2022-10-13 11:16
Do you use `java.awt.MouseInfo.getPointerInfo` directly, or this error appears when you use some Compose API?

If directly, then it is not related to Compose, because it is API from JDK.

It can be related to Compose, if you use native distribution when you run tests on CI. Do you use it?

When you just downgrade Compose and Kotlin, and leave other versions untouched, does the issue disappear?

**Comment by jamesreprise** [comment] 2022-10-13 12:12
Many thanks for your prompt reply.

> Do you use `java.awt.MouseInfo.getPointerInfo` directly, or this error appears when you use some Compose API?
Yes, we use it directly.

> It can be related to Compose, if you use native distribution when you run tests on CI. Do you use it?
No, we run our code directly on the JVM.

> When you just downgrade Compose and Kotlin, and leave other versions untouched, does the issue disappear?
Yes, the issue disappears and it works as-is currently. This is also a source of confusion for us.

**Comment by igordmn** [comment] 2022-10-13 12:44
`getPointerInfo` by itself can't be called in a headless environment, and Compose doesn't change this environment to `non-headless` state. My guess there is something wrongly cached in your build.

Can you narrow your the issue down, just calling `java.awt.MouseInfo.getPointerInfo` in the `main()` function (without calling `singleWindowApplication` or `application`)? It should crash, even with Compose 1.1.0-alpha04.

**Comment by jamesreprise** [comment] 2022-10-13 16:52
> Can you narrow your the issue down, just calling java.awt.MouseInfo.getPointerInfo in the main() function (without calling singleWindowApplication or application)? It should crash, even with Compose 1.1.0-alpha04

This is correct! Strange.

**Comment by igordmn** [comment] 2022-10-13 17:00
There was no behavior change in Compose, as it is not related to Compose. Something changed in your configuration.

You can look how we configure our CI. See [change in `blank.yml`](https://github.com/JetBrains/skiko/commit/90f73ca55a5960c5516f389ea9fd9ef5a4d20312) that disables headless mode on our CI.

**Comment by jamesreprise** [comment] 2022-10-14 15:37
> Also, my guess that you can use it in some place of code, that isn't called in 1.1, but is called in 1.2.
>
> Could you replace `java.awt.MouseInfo.getPointerInfo` by, for example, `throw RuntimeException()` and make a reproducer that crashes on 1.2, and doesn't crash on 1.1?

Correct again. I will work on providing a minimal reproducible build. In the mean time, do you have a working theory as to why this is happening?

**Comment by igordmn** [comment] 2022-10-14 15:38
> do you have a working theory

No, it can be anything.

**Comment by igordmn** [comment] 2022-11-15 20:53
Closing as the crash in the issue is a valid crash. If you find a code that doesn't behave as expected, create a new issue.

**Closed by igordmn** 2022-11-15 20:53 UTC

**Comment by okushnikov** [comment] 2024-07-14 17:00
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2398">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
